apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vessels.flotilla.work
spec:
  group: flotilla.work
  scope: Namespaced
  names:
    plural: vessels
    singular: vessel
    kind: Vessel
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Convoy
          type: string
          jsonPath: .spec.convoy_ref
        - name: Vessel
          type: string
          jsonPath: .spec.vessel_name
        - name: Phase
          type: string
          jsonPath: .status.phase
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
