mod admission;
pub mod agent_adapter;
pub mod agents;
pub mod aggregator_projection;
pub mod attachable;
pub mod awareness_projection;
pub mod change_request_observer;
pub mod checkout_integration;
pub mod config;
pub mod convert;
pub mod daemon;
pub mod data;
pub mod environment_manager;
pub mod executor;
pub mod hop_chain;
pub mod host_identity;
pub(crate) mod host_registry;
pub mod host_summary;
pub mod in_process;
pub mod leaf_engine;
pub mod log_file;
pub mod model;
pub(crate) mod observed_resources;
pub mod ops_entry;
pub mod path_context;
pub mod path_policy;
pub mod placement_policy;
pub mod project_declaration;
pub mod provider_data;
pub mod providers;
pub mod query_registry;
pub mod regard_lifecycle;
pub(crate) mod repo_state;
pub mod repository_inspection;
pub mod resolve;
pub mod salience;
mod scoped_store;
pub mod step;
pub mod template;
pub mod terminal_manager;

pub const DAEMON_LIFECYCLE_LOCK_FILE: &str = "flotillad-lifecycle.lock";

// Re-export shared infrastructure and host types for convenience.
pub use flotilla_protocol::HostName;
pub use flotilla_resources::tls;
