pub mod agent_adapter;
pub mod agents;
pub mod aggregator_projection;
pub mod attachable;
pub mod awareness_projection;
pub mod checkout_integration;
pub mod config;
pub mod convert;
pub mod daemon;
pub mod data;
pub mod delta;
pub mod environment_manager;
pub mod executor;
pub mod hop_chain;
pub mod host_identity;
pub(crate) mod host_registry;
pub mod host_summary;
pub mod in_process;
pub mod log_file;
pub mod merge;
pub mod model;
pub(crate) mod observed_resources;
pub mod path_context;
pub mod path_policy;
pub mod provider_data;
pub mod providers;
pub mod query_registry;
pub mod refresh;
pub(crate) mod repo_state;
pub mod repository_inspection;
pub mod resolve;
mod scoped_store;
pub mod step;
pub mod template;
pub mod terminal_manager;

// Re-export host types from protocol for convenience.
pub use flotilla_protocol::HostName;
