[package]
name = "flotilla-tls"
version = "0.1.0"
edition = "2021"
license.workspace = true
[features]
default = []
aws-lc-provider = ["rustls/aws_lc_rs"]
[dependencies]
reqwest = { workspace = true }
rustls = { workspace = true }
[lints]
workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
flotilla-build-features = { path = "../flotilla-build-features" }
flotilla-build-features-async = { path = "../flotilla-build-features-async" }
flotilla-build-features-base = { path = "../flotilla-build-features-base" }
flotilla-build-features-http = { path = "../flotilla-build-features-http" }
flotilla-build-features-os = { path = "../flotilla-build-features-os" }
flotilla-build-features-tracing = { path = "../flotilla-build-features-tracing" }
flotilla-build-features-types = { path = "../flotilla-build-features-types" }
[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
flotilla-build-features-logging = { path = "../flotilla-build-features-logging" }
