[package]
name = "flotilla-credentials-testkit"
version = "0.1.0"
edition = "2021"
license.workspace = true
publish = false

[dependencies]


[lints]
workspace = true

[dev-dependencies]
flotilla-build-features = { path = "../flotilla-build-features" }
flotilla-build-features-async = { path = "../flotilla-build-features-async" }
tokio = { workspace = true, features = ["test-util"] }
