use std::{
    path::{Path, PathBuf},
    time::Duration,
};

use clap::{CommandFactory, FromArgMatches, Parser};
use color_eyre::Result;
use flotilla_client::endpoint::{remote_daemon_from, DaemonEndpoint, SshEndpoint};
use flotilla_core::path_policy::{daemon_socket_path, PathPolicy};

/// Flotilla: TUI dashboard for managing development workspaces
#[derive(Parser)]
#[command(name = "flotilla", version)]
pub struct Cli {
    /// Git repo roots (repeatable; auto-detected from cwd if omitted)
    #[arg(long)]
    pub repo_root: Vec<PathBuf>,

    /// Daemon identity root (config and state use ROOT/config and ROOT/state)
    #[arg(long, conflicts_with_all = ["config_dir", "state_dir"])]
    pub root: Option<PathBuf>,

    /// Config directory (commands that may start a daemon also require --state-dir)
    #[arg(long, conflicts_with = "root")]
    pub config_dir: Option<PathBuf>,

    /// State directory (commands that may start a daemon also require --config-dir)
    #[arg(long, conflicts_with = "root")]
    pub state_dir: Option<PathBuf>,

    /// Socket path (default: ${config_dir}/run/flotilla.sock)
    #[arg(long)]
    pub socket: Option<PathBuf>,

    /// Use a daemon on another host: ssh://[user@]host[:port][/path/to/flotilla]
    /// (default: $FLOTILLA_DAEMON). Never spawns a local daemon; hooks and
    /// daemon lifecycle commands still act on this host.
    #[arg(long, conflicts_with = "socket")]
    pub daemon: Option<String>,

    /// Theme name (catppuccin-mocha, classic)
    #[arg(long)]
    pub theme: Option<String>,

    /// Output as JSON instead of human-readable text
    #[arg(long, global = true)]
    pub json: bool,

    /// Repository context (project member alias or forge slug; inferred inside an observed checkout)
    #[arg(long)]
    pub repo: Option<String>,

    #[command(subcommand)]
    pub command: Option<SubCommand>,
}

// Variants with arguments take an `Args` struct rather than inline fields, so
// clap builds each variant's arguments in its own call. Inline fields share
// one frame per enum, which overflowed Windows' 1 MiB main thread in
// unoptimised builds (#2588).
// Parsed once per process, so the size gap between `Domain` and the other
// variants costs nothing; boxing would only add derefs to every match.
#[allow(clippy::large_enum_variant)]
#[derive(clap::Subcommand)]
pub enum SubCommand {
    /// Run the daemon server
    Daemon(DaemonArgs),
    /// Open the TUI scoped to one View (e.g. `flotilla view convoys/flotilla`).
    ///
    /// Scoped mode shows exactly that View: no tab bar, and the persisted
    /// open-view set is untouched. This is the deep-link entry Presentation
    /// Manager recipes embed (ADR 0013).
    View(ViewArgs),
    /// Print repo list and state
    Status,
    /// Stream daemon events to stdout
    Watch,
    /// Block until one condition leaf becomes true
    Wait(WaitArgs),
    /// Show the daemon's current multi-host routing view
    Topology(TopologyArgs),
    /// Read structured daemon logs from this host or a peer
    Logs(LogsArgs),
    /// Show fleet-wide host health without collapsing independent observations
    Fleet {
        #[command(subcommand)]
        command: Option<FleetSubCommand>,
    },
    /// List convoy vessels and crew sessions
    Ls(LsArgs),
    /// Attach to a running convoy crew session
    Attach(AttachArgs),
    /// Receive agent hook events (called by agent hook systems)
    Hook(HookArgs),
    /// Install or uninstall agent hook configuration
    Hooks {
        #[command(subcommand)]
        command: HooksSubCommand,
    },
    /// Presentation-manager integration
    Pm {
        #[command(subcommand)]
        command: PmSubCommand,
    },
    /// Roll changed standing-convoy declarations at an operator-chosen boundary
    Ensure {
        #[command(subcommand)]
        command: EnsureSubCommand,
    },
    /// Inspect raw daemon resources
    Resource {
        #[command(subcommand)]
        command: ResourceSubCommand,
    },
    /// Inspect manifest document reconciliation
    Manifest {
        #[command(subcommand)]
        command: ManifestSubCommand,
    },
    /// Store and retrieve crew artifacts
    Artifact {
        #[command(subcommand)]
        command: ArtifactSubCommand,
    },
    /// List recent object-scoped events fleet-wide
    Events(EventsArgs),
    // --- Domain nouns (generated by flotilla-commands) ---
    #[command(flatten)]
    Domain(DomainCommand),

    /// Bridge stdio to this host's daemon socket (hidden; run over SSH by `--daemon ssh://...`)
    #[command(hide = true)]
    DaemonBridge,
    /// Generate completions (hidden, called by shell scripts)
    #[command(hide = true)]
    Complete(CompleteArgs),
    /// Output shell completion setup scripts
    Completions(CompletionsArgs),
}

#[derive(clap::Args)]
pub struct DaemonArgs {
    #[command(subcommand)]
    pub command: Option<DaemonSubCommand>,
    /// Idle timeout in seconds (0 = no timeout)
    #[arg(long, default_value = "300")]
    pub timeout: u64,
}

#[derive(clap::Args)]
pub struct ViewArgs {
    /// View address: `overview`, `repo/<authority>/<path>`, `convoys/<namespace>`, ...
    /// A `flotilla://` prefix is accepted.
    pub address: String,
}

#[derive(clap::Args)]
pub struct WaitArgs {
    /// Condition leaf; repeat to wait for any leaf (OR)
    #[arg(long = "for", required = true)]
    pub leaves: Vec<flotilla_protocol::Leaf>,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Require claim evidence observed at or after this RFC3339 instant
    ///
    /// Observation and claim leaves remain Unknown until their evidence
    /// is at least this fresh.
    #[arg(long)]
    pub fresher_than: Option<chrono::DateTime<chrono::Utc>>,
    /// Maximum seconds to block
    #[arg(long)]
    pub timeout: Option<u64>,
}

#[derive(clap::Args)]
pub struct TopologyArgs {
    /// Output the topology as a Graphviz DOT graph
    #[arg(long, conflicts_with = "json")]
    pub dot: bool,
}

#[derive(clap::Args)]
pub struct LogsArgs {
    /// Peer host name; omit to read this host
    #[arg(long)]
    pub host: Option<String>,
    /// Only show records this old or newer (for example `2h` or `30m`)
    #[arg(long, value_parser = parse_log_duration)]
    pub since: Option<Duration>,
    /// Minimum level: trace, debug, info, warn, or error
    #[arg(long, value_parser = ["trace", "debug", "info", "warn", "error"])]
    pub level: Option<String>,
    /// Exact tracing module target and its children
    #[arg(long)]
    pub target: Option<String>,
}

#[derive(clap::Args)]
pub struct LsArgs {
    /// Show only one project's convoys
    #[arg(long, conflicts_with = "all")]
    pub project: Option<String>,
    /// Show the whole fleet, including inside a crew
    #[arg(long, conflicts_with = "project")]
    pub all: bool,
}

#[derive(clap::Args)]
pub struct AttachArgs {
    /// Observe without taking the controller seat from another client
    #[arg(long, conflicts_with_all = ["strict", "take"])]
    pub watch: bool,
    /// Refuse when another attachment holds the controller seat
    #[arg(long, conflicts_with_all = ["watch", "take"])]
    pub strict: bool,
    /// Take control and demote the current controller to watcher
    #[arg(long, conflicts_with_all = ["watch", "strict"])]
    pub take: bool,
    /// Convoy, vessel, role, terminal session, or unique prefix
    pub reference: String,
    /// Internal attach mode used by temporary TUI excursions.
    #[arg(long, hide = true)]
    pub transient: bool,
    /// Restrict internal attach resolution to the daemon owning this row.
    #[arg(long, hide = true)]
    pub host: Option<String>,
}

#[derive(clap::Args)]
pub struct HookArgs {
    /// Agent harness name (e.g. claude-code, codex, gemini)
    pub harness: String,
    /// Event type (e.g. session-start, stop, notification)
    pub event_type: String,
    /// Codex notify supplies its JSON payload as one command argument.
    pub payload: Option<String>,
}

#[derive(clap::Args)]
pub struct EventsArgs {
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the query to a peer host
    #[arg(long)]
    pub host: Option<String>,
    /// Show only events authored by the queried host
    #[arg(long)]
    pub local_only: bool,
}

#[derive(clap::Args)]
pub struct CompleteArgs {
    /// The input line to complete
    pub line: String,
    /// Cursor position within the line
    #[arg(default_value = "0")]
    pub cursor_pos: usize,
}

#[derive(clap::Args)]
pub struct CompletionsArgs {
    /// Shell type
    #[arg(value_enum)]
    pub shell: CompletionShell,
}

/// Domain nouns, flattened into `SubCommand`. Keeping them in their own enum
/// lets clap build them in a separate call, which keeps unoptimised stack
/// frames small (#2588).
#[derive(clap::Subcommand)]
pub enum DomainCommand {
    /// Manage repositories
    Repo(flotilla_commands::commands::repo::RepoNoun),
    /// Manage environments
    Environment(flotilla_commands::commands::environment::EnvironmentNoun),
    /// Manage checkouts
    Checkout(flotilla_commands::commands::checkout::CheckoutNoun),
    /// Manage convoys
    Convoy(flotilla_commands::commands::convoy::ConvoyNoun),
    /// Inspect proposed dispatch work
    Dispatch(flotilla_commands::commands::dispatch::DispatchNoun),
    /// Communicate with crew members
    Crew(flotilla_commands::commands::crew::CrewNoun),
    /// Inspect live message relationships
    Message(MessageNoun),
    /// Code review (alias on CrNoun itself, not duplicated here)
    Cr(flotilla_commands::commands::cr::CrNoun),
    /// Issues
    Issue(flotilla_commands::commands::issue::IssueNoun),
    /// Cloud agents
    Agent(flotilla_commands::commands::agent::AgentNoun),
    /// Manage and route to hosts
    Host(flotilla_commands::commands::host::HostNounPartial),
    /// Inspect fulfilment kinds and live facts
    Fulfilment(flotilla_commands::commands::fulfilment::FulfilmentNoun),
    /// Manage workflow templates
    WorkflowTemplate(flotilla_commands::commands::workflow_template::WorkflowTemplateNoun),
    /// Manage projects
    Project(flotilla_commands::commands::project::ProjectNoun),
}

#[derive(clap::Args)]
pub struct MessageNoun {
    #[command(subcommand)]
    pub verb: MessageVerb,
}

#[derive(clap::Subcommand)]
pub enum MessageVerb {
    /// Show your own address, supervision chain and reachable crews
    Contacts {
        #[arg(long)]
        crew_id: Option<String>,
        #[arg(long)]
        namespace: Option<String>,
        #[arg(long)]
        convoy: Option<String>,
        #[arg(long)]
        vessel: Option<String>,
        #[arg(long)]
        role: Option<String>,
    },
}

impl MessageNoun {
    pub fn resolve(self) -> std::result::Result<flotilla_commands::Resolved, String> {
        let MessageVerb::Contacts { crew_id, namespace, convoy, vessel, role } = self.verb;
        let context = flotilla_protocol::CrewCommandContext {
            crew_id: crew_id.or_else(|| std::env::var("FLOTILLA_CREW_ID").ok()),
            namespace,
            convoy,
            vessel_ref: vessel,
            role,
        };
        Ok(flotilla_commands::Resolved::Ready(
            flotilla_protocol::Command::builder().action(flotilla_protocol::CommandAction::QueryMessageContacts { context }).build(),
        ))
    }
}

impl DomainCommand {
    pub fn resolve(self) -> Result<flotilla_commands::Resolved> {
        match self {
            DomainCommand::Repo(noun) => noun.resolve(),
            DomainCommand::Environment(noun) => noun.resolve(),
            DomainCommand::Checkout(noun) => noun.resolve(),
            DomainCommand::Convoy(noun) => noun.resolve(),
            DomainCommand::Dispatch(noun) => noun.resolve(),
            DomainCommand::Message(noun) => noun.resolve(),
            DomainCommand::Crew(noun) => noun.resolve_with_crew_id(std::env::var("FLOTILLA_CREW_ID").ok()),
            DomainCommand::Cr(noun) => noun.resolve(),
            DomainCommand::Issue(noun) => noun.resolve(),
            DomainCommand::Agent(noun) => noun.resolve(),
            DomainCommand::Host(partial) => {
                use flotilla_commands::Refinable;
                partial.refine().and_then(|noun| noun.resolve())
            }
            DomainCommand::Fulfilment(noun) => noun.resolve(),
            DomainCommand::WorkflowTemplate(noun) => noun.resolve(),
            DomainCommand::Project(noun) => noun.resolve(),
        }
        .map_err(|e| color_eyre::eyre::eyre!(e))
    }
}

#[derive(clap::Subcommand)]
pub enum ArtifactSubCommand {
    /// Store a crew artifact from a file the daemon can read
    #[command(
        long_about = "Store a crew artifact from a file path. The daemon reads the file; pass a path, not inline content.\n\nKinds: explainer (change explanation), decision-ledger (choices and alternatives), review-round (one review verdict), brief (handoff context), review-bundle (durable review evidence), recording, test-report, raw-test-output (bulky, short-retention evidence).\n\nPrefer Markdown for prose; self-contained HTML is also supported. --about names the exact subject, such as a commit or review round. --summary records small scalar facts for workflow conditions; keep detailed prose in the file."
    )]
    Put {
        #[arg(long)]
        kind: String,
        #[arg(long)]
        about: Option<String>,
        #[arg(long = "summary", value_parser = parse_artifact_summary)]
        summary: Vec<(String, serde_json::Value)>,
        file: PathBuf,
    },
    Get {
        reference: String,
        #[arg(short = 'o', long)]
        output: Option<PathBuf>,
    },
    List {
        #[arg(long)]
        convoy: Option<String>,
        #[arg(long)]
        kind: Option<String>,
        #[arg(long)]
        about: Option<String>,
    },
}

fn parse_artifact_summary(value: &str) -> Result<(String, serde_json::Value), String> {
    let (key, value) = value.split_once('=').ok_or_else(|| "summary must be key=value".to_string())?;
    if key.is_empty() {
        return Err("summary key must be nonempty".into());
    }
    let parsed = serde_json::from_str(value).unwrap_or_else(|_| serde_json::Value::String(value.to_string()));
    if !parsed.is_string() && !parsed.is_number() && !parsed.is_boolean() {
        return Err("summary value must be a string, number, or boolean".into());
    }
    Ok((key.to_string(), parsed))
}

#[derive(clap::Subcommand)]
pub enum DaemonSubCommand {
    /// Gracefully stop the running daemon
    Stop,
    /// Toggle the fleet launchd agent for local daemon development
    DevMode {
        #[command(subcommand)]
        command: DevModeSubCommand,
    },
}

#[derive(clap::Subcommand)]
pub enum DevModeSubCommand {
    /// Disable and stop the fleet agent so a dev-built daemon may spawn
    Enable,
    /// Re-enable and start the fleet agent
    Disable,
}

#[derive(Clone, clap::ValueEnum)]
pub enum CompletionShell {
    Bash,
    Zsh,
    Fish,
}

#[derive(clap::Subcommand)]
pub enum PmSubCommand {
    /// Run the manifest metadata-patch connector for the enclosing PM
    Connect {
        /// Zellij binary for pipe delivery (default: $ZELLIJ_BIN, then `zellij`)
        #[arg(long)]
        zellij_bin: Option<String>,
        /// Restrict pipe delivery to one plugin instance
        #[arg(long)]
        plugin_url: Option<String>,
        /// Publish to a Wheelhouse Unix socket (Windows: named pipe) instead of zellij pipes
        #[arg(long)]
        wheelhouse_socket: Option<PathBuf>,
        /// Executable path or name the PM runs (default: this connector executable)
        ///
        /// The recipe executes on the PM host; use this override when that host
        /// needs a different path or wrapper.
        #[arg(long)]
        flotilla_bin: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum HooksSubCommand {
    /// Install hooks for an agent harness
    Install {
        /// Agent harness (e.g. claude-code)
        harness: String,
        /// Install to user settings (~/.claude/settings.json)
        #[arg(long)]
        user: bool,
        /// Install to project settings (.claude/settings.json, committed)
        #[arg(long)]
        project: bool,
        /// Install to local project settings (.claude/settings.local.json, gitignored)
        #[arg(long)]
        local: bool,
        /// Show plugin marketplace install instructions instead
        #[arg(long)]
        plugin: bool,
    },
    /// Remove hooks for an agent harness
    Uninstall {
        /// Agent harness (e.g. claude-code)
        harness: String,
        /// Remove from user settings
        #[arg(long)]
        user: bool,
        /// Remove from project settings
        #[arg(long)]
        project: bool,
        /// Remove from local project settings
        #[arg(long)]
        local: bool,
    },
}

#[derive(clap::Subcommand)]
pub enum ManifestSubCommand {
    /// List document states for all roots or one root
    Status {
        root: Option<String>,
        #[arg(long, default_value = "flotilla")]
        namespace: String,
        #[arg(long)]
        host: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum EnsureSubCommand {
    /// Replace one drifted running generation, or all drifted ensures
    Roll {
        #[arg(required_unless_present = "drifted", conflicts_with = "drifted")]
        name: Option<String>,
        #[arg(long)]
        drifted: bool,
        #[arg(long, default_value = "flotilla")]
        namespace: String,
        #[arg(long)]
        host: Option<String>,
    },
}

#[derive(clap::Subcommand)]
pub enum ResourceSubCommand {
    /// List resources of a kind
    List(ResourceListArgs),
    /// Create or update a raw resource document
    Apply(ResourceApplyArgs),
    /// Validate resource documents against this binary's schema
    Validate {
        /// Resource document or directory containing JSON/YAML manifests
        #[arg(required_unless_present = "from_daemon", conflicts_with = "from_daemon")]
        path: Option<PathBuf>,
        /// Validate the running daemon's stored records using this binary's schema
        #[arg(long)]
        from_daemon: bool,
        /// Resolve every CrewDefaults role and Project against this candidate skill catalog
        #[arg(long)]
        skill_catalog: Option<PathBuf>,
        /// Candidate skill supply directory containing .flotilla-sources.json
        #[arg(long, requires = "from_daemon")]
        skill_sources: Option<PathBuf>,
        /// JSON map of declared credential names to operator-supplied probe token files
        #[arg(long, requires = "from_daemon")]
        skill_probe_tokens: Option<PathBuf>,
        /// Read a peer's forwarded resource socket instead of the local daemon
        #[arg(long, requires = "from_daemon")]
        host: Option<String>,
    },
    /// Make the manifest overwrite a drifted live spec
    Sync(ResourceManifestResolutionArgs),
    /// Write the live spec back to its manifest
    Adopt(ResourceManifestResolutionArgs),
    /// Reset backoff and immediately reconcile one operator target.
    ///
    /// Interim fallback for dependencies that cannot be named by a refusal:
    /// use `resource apply` to touch an annotation and wake reconciliation by
    /// bumping the object's resource version.
    ReconcileNow(ResourceReconcileNowArgs),
    /// Replace the status subresource after typed validation
    PatchStatus(ResourceStatusPatchArgs),
    /// Close a held or exhausted Message batch, preserving its submission audit.
    FailMessageBatch(MessageFailBatchArgs),
    /// Get one resource by name
    Get(ResourceGetArgs),
    /// Explain the charter source and applied revision that authored a record
    Explain(ResourceGetArgs),
    /// Delete exactly one raw resource object, bypassing lifecycle gates
    Delete(ResourceDeleteArgs),
    /// Remove a declared transport remote from a Repository
    RemoveRemote(ResourceRemoveRemoteArgs),
    /// Remove standing multi-authored Host and PlacementPolicy records from non-home roots
    DedupSweep(ResourceDedupSweepArgs),
    /// Watch resources of a kind
    Watch(ResourceWatchArgs),
}

#[derive(clap::Args)]
pub struct ResourceDedupSweepArgs {
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
}

#[derive(clap::Args, bon::Builder)]
pub struct ResourceListArgs {
    /// Resource kind or plural name, e.g. convoys or WorkflowTemplate
    pub kind: String,
    /// Show only resources belonging to this project
    #[arg(long)]
    pub project: Option<String>,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the query to a peer host
    #[arg(long)]
    pub host: Option<String>,
    /// Show only records authored by the queried host
    #[arg(long)]
    pub local_only: bool,
    /// Include read-only replicas from peer roots (the default)
    #[arg(long, conflicts_with = "local_only")]
    pub include_replicas: bool,
}

#[derive(clap::Args)]
pub struct ResourceGetArgs {
    /// Resource kind or plural name, e.g. convoys or WorkflowTemplate
    pub kind: String,
    /// Resource name
    pub name: String,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the query to a peer host
    #[arg(long)]
    pub host: Option<String>,
}

#[derive(clap::Args)]
pub struct ResourceReconcileNowArgs {
    /// Resource kind, or manifest-root
    pub kind: String,
    /// Resource or manifest-root name
    pub name: String,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the operation to a peer host
    #[arg(long)]
    pub host: Option<String>,
}

#[derive(clap::Args)]
pub struct ResourceManifestResolutionArgs {
    /// Exact resource kind or plural name
    pub kind: String,
    /// Exact resource name
    pub name: String,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the mutation to a peer host
    #[arg(long)]
    pub host: Option<String>,
}

#[derive(clap::Args, bon::Builder)]
pub struct ResourceWatchArgs {
    /// Resource kind or plural name, e.g. convoys or WorkflowTemplate
    pub kind: String,
    /// Restrict the stream to one resource name
    pub name: Option<String>,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the watch to a peer host
    #[arg(long)]
    pub host: Option<String>,
    /// Include read-only replicas from peer roots
    #[arg(long)]
    pub include_replicas: bool,
    /// Resume strictly after a cursor emitted by an earlier read or watch
    #[arg(long)]
    pub from_cursor: Option<flotilla_protocol::ResourceCursor>,
}

#[derive(clap::Args)]
pub struct ResourceDeleteArgs {
    /// Exact resource kind or plural name
    pub kind: String,
    /// Exact resource name
    pub name: String,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Collect a read-only replica from this origin root
    #[arg(long, value_name = "ORIGIN_ROOT")]
    pub replica: Option<String>,
    /// Delete the authoritative record on this peer host (including incorrectly authored residue)
    #[arg(long)]
    pub host: Option<String>,
}

#[derive(clap::Args)]
pub struct ResourceRemoveRemoteArgs {
    /// Repository resource name (its stable Repository key)
    pub name: String,
    /// Remote URL to remove
    pub remote: String,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the mutation to a peer host
    #[arg(long)]
    pub host: Option<String>,
}

#[derive(clap::Args)]
pub struct ResourceApplyArgs {
    /// Resource document path (JSON or YAML)
    #[arg(short, long)]
    pub file: PathBuf,
    /// Default namespace when metadata.namespace is omitted
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the mutation to a peer host
    #[arg(long)]
    pub host: Option<String>,
}

#[derive(clap::Args)]
pub struct MessageFailBatchArgs {
    /// A member of the held batch
    pub name: String,
    /// Operator explanation retained in every member's status
    #[arg(long)]
    pub reason: String,
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    #[arg(long)]
    pub host: Option<String>,
}

#[derive(clap::Args)]
pub struct ResourceStatusPatchArgs {
    /// Exact resource kind or plural name
    pub kind: String,
    /// Exact resource name
    pub name: String,
    /// Status document path (JSON or YAML)
    #[arg(short, long)]
    pub file: PathBuf,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    pub namespace: String,
    /// Route the mutation to a peer host
    #[arg(long)]
    pub host: Option<String>,
}

#[derive(clap::Subcommand)]
pub enum FleetSubCommand {
    /// Confirm this wire generation's daemon responds with a local fleet row (never starts a daemon)
    Check,
    /// Show hosts grouped by wire generation (never starts a daemon)
    Spread,
    /// Prune local generations (caller must hold the fleet installer lock)
    Prune {
        #[arg(long)]
        fleet_root: PathBuf,
        #[arg(long, default_value = "3", allow_hyphen_values = true)]
        keep_others: String,
        #[arg(long)]
        dry_run: bool,
    },
    /// Run this generation's post-install cleat turnover after health confirmation
    PostInstall {
        #[arg(long)]
        cleat_bin: PathBuf,
        #[arg(long)]
        generation: String,
        #[arg(long)]
        diagnostics_dir: PathBuf,
    },
}

impl Cli {
    pub fn try_parse_with_version(version: &'static str, long_version: &'static str) -> Result<Self, clap::Error> {
        let matches = Self::command().version(version).long_version(long_version).try_get_matches()?;
        Self::from_arg_matches(&matches)
    }

    pub fn client_paths(&self) -> Result<CliPaths, String> {
        let policy = PathPolicy::from_process_env();
        let environment_socket = std::env::var_os("FLOTILLA_DAEMON_SOCKET");
        let (config_dir, state_dir) = client_dirs_from(
            self.root.as_deref(),
            self.config_dir.as_deref(),
            self.state_dir.as_deref(),
            policy.config_dir.as_path(),
            policy.state_dir.as_path(),
            environment_socket.as_deref(),
        )?;
        let socket_path = socket_path_from(self.socket.as_deref(), &config_dir, environment_socket.as_deref());
        Ok(CliPaths { config_dir, state_dir, socket_path })
    }

    pub fn daemon_paths(&self) -> Result<CliPaths, String> {
        let policy = PathPolicy::from_process_env();
        daemon_paths_from(
            self.root.as_deref(),
            self.config_dir.as_deref(),
            self.state_dir.as_deref(),
            self.socket.as_deref(),
            policy.config_dir.as_path(),
            policy.state_dir.as_path(),
        )
    }

    pub fn socket_path(&self) -> PathBuf {
        // Socket-only commands never spawn, so they may select a socket through
        // --config-dir without resolving the daemon's paired state directory.
        let policy = PathPolicy::from_process_env();
        let config_dir = self
            .root
            .as_deref()
            .map(|root| root.join("config"))
            .or_else(|| self.config_dir.clone())
            .unwrap_or_else(|| policy.config_dir.into_path_buf());
        socket_path_from(self.socket.as_deref(), &config_dir, std::env::var_os("FLOTILLA_DAEMON_SOCKET").as_deref())
    }

    /// The remote daemon selected by `--daemon` or `FLOTILLA_DAEMON`, if any.
    pub fn remote_daemon(&self) -> Result<Option<SshEndpoint>, String> {
        remote_daemon_from(self.daemon.as_deref(), std::env::var("FLOTILLA_DAEMON").ok().as_deref(), self.socket.is_some())
    }

    /// The daemon socket-only commands talk to: a remote endpoint, else this host's socket.
    pub fn daemon_endpoint(&self) -> Result<DaemonEndpoint, String> {
        Ok(self.remote_daemon()?.map(DaemonEndpoint::Ssh).unwrap_or_else(|| DaemonEndpoint::Local(self.socket_path())))
    }

    /// Refuse a remote endpoint for commands that manage this host's daemon.
    pub fn require_local_daemon(&self, command: &str) -> Result<()> {
        match self.remote_daemon().map_err(|error| color_eyre::eyre::eyre!(error))? {
            Some(remote) => Err(color_eyre::eyre::eyre!(
                "`{command}` manages this host's daemon and cannot target {remote}; drop --daemon or unset FLOTILLA_DAEMON"
            )),
            None => Ok(()),
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub struct CliPaths {
    pub config_dir: PathBuf,
    pub state_dir: PathBuf,
    pub socket_path: PathBuf,
}

fn client_dirs_from(
    explicit_root: Option<&Path>,
    explicit_config_dir: Option<&Path>,
    explicit_state_dir: Option<&Path>,
    default_config_dir: &Path,
    default_state_dir: &Path,
    environment_socket: Option<&std::ffi::OsStr>,
) -> Result<(PathBuf, PathBuf), String> {
    if explicit_root.is_none() && explicit_config_dir.is_none() && explicit_state_dir.is_none() {
        if let Some(dirs) = environment_socket.map(Path::new).and_then(flotilla_core::path_policy::scoped_daemon_dirs) {
            return Ok(dirs);
        }
    }
    daemon_dirs_from(explicit_root, explicit_config_dir, explicit_state_dir, default_config_dir, default_state_dir)
}

fn daemon_dirs_from(
    explicit_root: Option<&Path>,
    explicit_config_dir: Option<&Path>,
    explicit_state_dir: Option<&Path>,
    default_config_dir: &Path,
    default_state_dir: &Path,
) -> Result<(PathBuf, PathBuf), String> {
    if let Some(root) = explicit_root {
        return Ok((root.join("config"), root.join("state")));
    }
    match (explicit_config_dir, explicit_state_dir) {
        (Some(config_dir), Some(state_dir)) => Ok((config_dir.to_path_buf(), state_dir.to_path_buf())),
        (None, None) => Ok((default_config_dir.to_path_buf(), default_state_dir.to_path_buf())),
        _ => Err("this command may start a daemon, so --config-dir and --state-dir must be supplied together; use --root to select both"
            .to_string()),
    }
}

fn socket_path_from(explicit: Option<&Path>, config_dir: &Path, environment: Option<&std::ffi::OsStr>) -> PathBuf {
    environment.map(PathBuf::from).or_else(|| explicit.map(PathBuf::from)).unwrap_or_else(|| daemon_socket_path(config_dir))
}

fn daemon_paths_from(
    explicit_root: Option<&Path>,
    explicit_config_dir: Option<&Path>,
    explicit_state_dir: Option<&Path>,
    explicit_socket: Option<&Path>,
    default_config_dir: &Path,
    default_state_dir: &Path,
) -> Result<CliPaths, String> {
    let (config_dir, state_dir) =
        daemon_dirs_from(explicit_root, explicit_config_dir, explicit_state_dir, default_config_dir, default_state_dir)?;
    let socket_path = explicit_socket.map(PathBuf::from).unwrap_or_else(|| daemon_socket_path(&config_dir));
    Ok(CliPaths { config_dir, state_dir, socket_path })
}

fn parse_log_duration(value: &str) -> Result<Duration, String> {
    humantime::parse_duration(value).map_err(|error| error.to_string())
}

pub fn attach_mode(watch: bool, strict: bool, take: bool) -> flotilla_protocol::commands::AttachMode {
    match (watch, strict, take) {
        (true, false, false) => flotilla_protocol::commands::AttachMode::Default,
        (false, true, false) => flotilla_protocol::commands::AttachMode::Strict,
        (false, false, true) => flotilla_protocol::commands::AttachMode::Take,
        (false, false, false) => flotilla_protocol::commands::AttachMode::PreferTake,
        _ => unreachable!("clap rejects conflicting attach seat options"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::{CommandFactory, Parser};

    use std::path::{Path, PathBuf};
    // daemons, using the resolved session/host rather than the daemon-local plan.
    // The documented one-way rollback recovery command must remain parseable.
    #[test]
    fn workflow_retirement_restoration_command_parses() {
        let parsed = Cli::try_parse_from(["flotilla", "resource", "apply", "--file", "/path/to/restore-0.json"])
            .expect("documented restoration command");
        assert!(matches!(parsed.command, Some(SubCommand::Resource {
            command: ResourceSubCommand::Apply(ResourceApplyArgs { file, .. })
        }) if file == Path::new("/path/to/restore-0.json")));
    }

    // Glue: explicit operator intent requires a reason and identifies a member.
    #[test]
    fn fail_message_batch_cli_requires_an_operator_reason() {
        let parsed = Cli::try_parse_from(["flotilla", "resource", "fail-message-batch", "held", "--reason", "cancel after inspection"])
            .expect("operator command");
        assert!(
            matches!(parsed.command, Some(SubCommand::Resource { command: ResourceSubCommand::FailMessageBatch(args) }) if args.name == "held" && args.reason == "cancel after inspection")
        );
        assert!(Cli::try_parse_from(["flotilla", "resource", "fail-message-batch", "held"]).is_err());
    }

    #[test]
    fn daemon_endpoint_conflicts_with_socket_and_bridge_is_hidden() {
        assert!(Cli::try_parse_from(["flotilla", "--daemon", "ssh://udder", "--socket", "/tmp/x.sock", "status"]).is_err());
        let bridge = Cli::try_parse_from(["flotilla", "--socket", "/tmp/x.sock", "daemon-bridge"]).expect("bridge parses");
        assert!(matches!(bridge.command, Some(SubCommand::DaemonBridge)));
        let help = Cli::command().render_help().to_string();
        assert!(!help.contains("daemon-bridge"), "daemon-bridge is internal: {help}");
    }

    // Lifecycle commands manage this host's daemon; a remote endpoint is refused,
    // never silently ignored.
    #[test]
    fn local_daemon_commands_refuse_a_remote_endpoint() {
        let cli = Cli::try_parse_from(["flotilla", "--daemon", "ssh://udder", "daemon", "stop"]).expect("parse");
        let error = cli.require_local_daemon("daemon stop").expect_err("remote endpoint refused").to_string();
        assert!(error.contains("this host's daemon") && error.contains("ssh://udder"), "{error}");
    }

    /// Windows gives the main thread 1 MiB of stack. Unoptimised clap-derive
    /// builders need frames that grow with the command tree, and the nested
    /// noun/verb derives add up along the deepest path (#2588). Parsing that
    /// path needed about 520 KiB when this budget was set. An overflow aborts the
    /// test binary with "thread 'cli-parse-stack-budget' has overflowed its
    /// stack": split large variants into `Args` structs rather than raising this.
    /// Frame sizes differ by platform and toolchain, so this is a portable
    /// growth tripwire; the Windows CI job running the binary is the
    /// authoritative check.
    #[test]
    fn cli_parse_fits_within_windows_main_thread_stack_budget() {
        const BUDGET: usize = 768 * 1024;
        std::thread::Builder::new()
            .name("cli-parse-stack-budget".into())
            .stack_size(BUDGET)
            .spawn(|| {
                for args in [
                    &["flotilla", "--version"][..],
                    &["flotilla", "status"][..],
                    &["flotilla", "convoy", "start", "--project", "p", "--name", "n", "--input", "k=v"][..],
                ] {
                    let _ = Cli::try_parse_from(args);
                }
            })
            .expect("spawn stack-budget thread")
            .join()
            .expect("CLI parsing completes within the stack budget");
    }

    #[test]
    fn ensure_roll_cli_accepts_one_ensure_or_all_drifted() {
        for args in [vec!["flotilla", "ensure", "roll", "demo--governor"], vec!["flotilla", "ensure", "roll", "--drifted"]] {
            Cli::try_parse_from(args).expect("explicit ensure roll should parse");
        }
        assert!(Cli::try_parse_from(["flotilla", "ensure", "roll"]).is_err());
        assert!(Cli::try_parse_from(["flotilla", "ensure", "roll", "demo--governor", "--drifted"]).is_err());
    }

    #[test]
    fn pm_connector_cli_leaves_flotilla_bin_unset_without_override() {
        let cli = Cli::try_parse_from(["flotilla", "pm", "connect", "--wheelhouse-socket", "/tmp/wheelhouse.sock"])
            .expect("parse connector command");
        let Some(SubCommand::Pm { command: PmSubCommand::Connect { flotilla_bin, .. } }) = cli.command else {
            panic!("expected pm connect command")
        };
        assert_eq!(flotilla_bin, None);
    }

    #[test]
    fn wait_cli_accepts_an_or_set_and_timeout() {
        let cli = Cli::try_parse_from([
            "flotilla",
            "wait",
            "--for",
            "convoy/demo .status.phase == Landed",
            "--for",
            "work/demo/implement .latest-claim.disposition == changes-pushed",
            "--timeout",
            "30",
        ])
        .expect("parse wait command");
        let Some(SubCommand::Wait(WaitArgs { leaves, timeout, .. })) = cli.command else { panic!("expected wait command") };
        assert_eq!(leaves.len(), 2);
        assert_eq!(timeout, Some(30));
    }

    #[test]
    fn cli_parses_topology_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "topology"]).expect("topology cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology(TopologyArgs { dot: false }))));
        assert!(!cli.json);
    }

    #[test]
    fn cli_parses_topology_with_global_json() {
        let cli = Cli::try_parse_from(["flotilla", "topology", "--json"]).expect("topology json should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology(TopologyArgs { dot: false }))));
        assert!(cli.json);
    }

    #[test]
    fn cli_parses_topology_dot() {
        let cli = Cli::try_parse_from(["flotilla", "topology", "--dot"]).expect("topology dot should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology(TopologyArgs { dot: true }))));
        assert!(!cli.json);
    }

    #[test]
    fn cli_parses_fleet_wide_events_view() {
        let cli = Cli::try_parse_from(["flotilla", "events", "--host", "kiwi", "--json"]).expect("events cli should parse");
        assert!(matches!(
            cli.command,
            Some(SubCommand::Events(EventsArgs { namespace, host: Some(host), local_only: false }))
                if namespace == "flotilla" && host == "kiwi"
        ));
        assert!(cli.json);
    }

    #[test]
    fn cli_parses_remote_filtered_logs() {
        let cli = Cli::try_parse_from([
            "flotilla",
            "logs",
            "--host",
            "feta",
            "--since",
            "2h",
            "--level",
            "warn",
            "--target",
            "flotilla_daemon::peer",
        ])
        .expect("logs cli should parse");

        assert!(matches!(
            cli.command,
            Some(SubCommand::Logs(LogsArgs {
                host: Some(host),
                since: Some(since),
                level: Some(level),
                target: Some(target),
            })) if host == "feta"
                && since == std::time::Duration::from_secs(7200)
                && level == "warn"
                && target == "flotilla_daemon::peer"
        ));
    }

    #[test]
    fn cli_parses_ls_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "ls"]).expect("ls cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Ls(LsArgs { project: None, all: false }))));
        let scoped = Cli::try_parse_from(["flotilla", "ls", "--project", "island"]).expect("scoped ls should parse");
        assert!(matches!(scoped.command, Some(SubCommand::Ls(LsArgs { project: Some(project), all: false })) if project == "island"));
        let all = Cli::try_parse_from(["flotilla", "ls", "--all"]).expect("fleet ls should parse");
        assert!(matches!(all.command, Some(SubCommand::Ls(LsArgs { project: None, all: true }))));
        assert!(Cli::try_parse_from(["flotilla", "ls", "--all", "--project", "island"]).is_err());
    }

    #[test]
    fn cli_parses_manifest_status() {
        let cli = Cli::try_parse_from(["flotilla", "manifest", "status", "manifest-123"]).expect("manifest status should parse");
        assert!(matches!(cli.command, Some(SubCommand::Manifest {
            command: super::ManifestSubCommand::Status { root: Some(root), namespace, host: None }
        }) if root == "manifest-123" && namespace == "flotilla"));
    }

    #[test]
    fn cli_parses_resource_subcommands() {
        let scoped = Cli::try_parse_from(["flotilla", "resource", "list", "convoys", "--project", "island"])
            .expect("project resource list should parse");
        assert!(matches!(
            scoped.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::List(ResourceListArgs { project: Some(project), .. })
            }) if project == "island"
        ));
        let list = Cli::try_parse_from(["flotilla", "resource", "list", "convoys", "--host", "feta"]).expect("resource list should parse");
        assert!(matches!(
            list.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::List(ResourceListArgs {
                    kind,
                    project: None,
                    namespace,
                    host: Some(host),
                    local_only: false,
                    include_replicas: false,
                })
            }) if kind == "convoys" && namespace == "flotilla" && host == "feta"
        ));

        let include_replicas = Cli::try_parse_from(["flotilla", "resource", "list", "hosts", "--include-replicas"])
            .expect("legacy explicit replica selection should still parse");
        assert!(matches!(
            include_replicas.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::List(ResourceListArgs {
                    kind,
                    project: None,
                    namespace,
                    host: None,
                    local_only: false,
                    include_replicas: true,
                })
            }) if kind == "hosts" && namespace == "flotilla"
        ));

        let get = Cli::try_parse_from(["flotilla", "resource", "get", "convoys", "demo", "--namespace", "ops"])
            .expect("resource get should parse");
        assert!(matches!(
            get.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Get(ResourceGetArgs { kind, name, namespace, host: None })
            }) if kind == "convoys" && name == "demo" && namespace == "ops"
        ));

        let reconcile = Cli::try_parse_from(["flotilla", "resource", "reconcile-now", "ConvoyEnsure", "quartermaster", "--host", "feta"])
            .expect("resource reconcile-now should parse");
        assert!(matches!(
            reconcile.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::ReconcileNow(ResourceReconcileNowArgs { kind, name, namespace, host: Some(host) })
            }) if kind == "ConvoyEnsure" && name == "quartermaster" && namespace == "flotilla" && host == "feta"
        ));

        let sync = Cli::try_parse_from(["flotilla", "resource", "sync", "projects", "cleat", "--namespace", "ops"])
            .expect("manifest sync should parse");
        assert!(matches!(
            sync.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Sync(ResourceManifestResolutionArgs { kind, name, namespace, host: None })
            }) if kind == "projects" && name == "cleat" && namespace == "ops"
        ));
        let adopt = Cli::try_parse_from(["flotilla", "resource", "adopt", "projects", "cleat", "--namespace", "ops"])
            .expect("manifest adopt should parse");
        assert!(matches!(
            adopt.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Adopt(ResourceManifestResolutionArgs { kind, name, namespace, host: None })
            }) if kind == "projects" && name == "cleat" && namespace == "ops"
        ));

        let delete =
            Cli::try_parse_from(["flotilla", "resource", "delete", "workflowtemplates", "scratch", "--namespace", "ops", "--host", "feta"])
                .expect("resource delete should parse");
        assert!(matches!(
            delete.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Delete(ResourceDeleteArgs { kind, name, namespace, replica: None, host: Some(host) })
            }) if kind == "workflowtemplates" && name == "scratch" && namespace == "ops" && host == "feta"
        ));

        let collect =
            Cli::try_parse_from(["flotilla", "resource", "delete", "convoys", "orphan", "--replica", "retired-root", "--host", "feta"])
                .expect("replica collection should parse");
        assert!(matches!(
            collect.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Delete(ResourceDeleteArgs {
                    replica: Some(origin),
                    host: Some(host),
                    ..
                })
            }) if origin == "retired-root" && host == "feta"
        ));

        let apply = Cli::try_parse_from(["flotilla", "resource", "apply", "-f", "demand.yaml", "--namespace", "ops", "--host", "feta"])
            .expect("resource apply should parse");
        assert!(matches!(
            apply.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Apply(ResourceApplyArgs { file, namespace, host: Some(host) })
            }) if file.as_path() == Path::new("demand.yaml") && namespace == "ops" && host == "feta"
        ));

        let patch_status =
            Cli::try_parse_from(["flotilla", "resource", "patch-status", "usages", "usage-ada", "-f", "status.json", "--namespace", "ops"])
                .expect("resource patch-status should parse");
        assert!(matches!(
            patch_status.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::PatchStatus(ResourceStatusPatchArgs { kind, name, file, namespace, host: None })
            }) if kind == "usages"
                && name == "usage-ada"
                && file.as_path() == Path::new("status.json")
                && namespace == "ops"
        ));

        let watch = Cli::try_parse_from([
            "flotilla",
            "resource",
            "watch",
            "terminalsessions",
            "session-a",
            "--from-cursor",
            &flotilla_protocol::ResourceCursor::from_position("7", None).to_string(),
            "--json",
        ])
        .expect("resource watch should parse");
        assert!(watch.json);
        assert!(matches!(
            watch.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Watch(ResourceWatchArgs {
                    kind,
                    name: Some(name),
                    namespace,
                    host: None,
                    include_replicas: false,
                    from_cursor: Some(_),
                })
            }) if kind == "terminalsessions" && name == "session-a" && namespace == "flotilla"
        ));
    }

    #[test]
    fn resource_validate_cli_requires_one_source_and_qualifies_peer_hosts() {
        let file = Cli::try_parse_from(["flotilla", "resource", "validate", "resource.yaml"]).expect("path validation should parse");
        assert!(matches!(
            file.command,
            Some(SubCommand::Resource { command: ResourceSubCommand::Validate { path: Some(_), from_daemon: false, host: None, .. } })
        ));
        let daemon = Cli::try_parse_from(["flotilla", "resource", "validate", "--from-daemon", "--host", "feta"])
            .expect("peer validation should parse");
        assert!(
            matches!(daemon.command, Some(SubCommand::Resource { command: ResourceSubCommand::Validate { path: None, from_daemon: true, host: Some(host), .. } }) if host == "feta")
        );
        for args in [
            vec!["flotilla", "resource", "validate"],
            vec!["flotilla", "resource", "validate", "--host", "feta"],
            vec!["flotilla", "resource", "validate", "--from-daemon", "resource.yaml"],
        ] {
            assert!(Cli::try_parse_from(args).is_err());
        }
    }

    #[test]
    fn cli_parses_attach_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "attach", "convoy-a/implement/coder"]).expect("attach cli should parse");
        assert!(matches!(
            cli.command,
            Some(SubCommand::Attach(AttachArgs { reference, watch: false, strict: false, take: false, transient: false, host: None }))
                if reference == "convoy-a/implement/coder"
        ));
        assert_eq!(attach_mode(false, false, false), flotilla_protocol::commands::AttachMode::PreferTake);
    }

    #[test]
    fn cli_parses_controller_seat_flags() {
        let strict =
            Cli::try_parse_from(["flotilla", "attach", "--strict", "convoy-a/implement/coder"]).expect("strict attach cli should parse");
        assert!(matches!(
            strict.command,
            Some(SubCommand::Attach(AttachArgs { reference, watch: false, strict: true, take: false, transient: false, host: None }))
                if reference == "convoy-a/implement/coder"
        ));
        let take = Cli::try_parse_from(["flotilla", "attach", "--take", "convoy-a/implement/coder"]).expect("take attach cli should parse");
        assert!(matches!(
            take.command,
            Some(SubCommand::Attach(AttachArgs { reference, watch: false, strict: false, take: true, transient: false, host: None }))
                if reference == "convoy-a/implement/coder"
        ));
        let watch =
            Cli::try_parse_from(["flotilla", "attach", "--watch", "convoy-a/implement/coder"]).expect("watch attach cli should parse");
        assert!(matches!(
            watch.command,
            Some(SubCommand::Attach(AttachArgs { reference, watch: true, strict: false, take: false, transient: false, host: None }))
                if reference == "convoy-a/implement/coder"
        ));
        assert_eq!(attach_mode(true, false, false), flotilla_protocol::commands::AttachMode::Default);
        assert!(Cli::try_parse_from(["flotilla", "attach", "--strict", "--take", "convoy-a/implement/coder"]).is_err());
        assert!(Cli::try_parse_from(["flotilla", "attach", "--watch", "--take", "convoy-a/implement/coder"]).is_err());
    }

    #[test]
    fn contained_cli_socket_environment_takes_precedence() {
        assert_eq!(
            socket_path_from(
                Some(Path::new("/explicit/flotilla.sock")),
                Path::new("/config"),
                Some(std::ffi::OsStr::new("/run/flotilla.sock")),
            ),
            PathBuf::from("/run/flotilla.sock"),
        );
    }

    #[test]
    fn default_socket_uses_a_dedicated_runtime_directory() {
        assert_eq!(socket_path_from(None, Path::new("/config"), None), PathBuf::from("/config/run/flotilla.sock"));
    }

    #[test]
    fn daemon_paths_use_only_explicit_values_and_policy_defaults() {
        assert_eq!(
            daemon_paths_from(
                None,
                None,
                None,
                Some(Path::new("/explicit/flotilla.sock")),
                Path::new("/default/config"),
                Path::new("/default/state"),
            )
            .expect("policy defaults form a complete identity"),
            CliPaths {
                config_dir: PathBuf::from("/default/config"),
                state_dir: PathBuf::from("/default/state"),
                socket_path: PathBuf::from("/explicit/flotilla.sock"),
            },
        );
    }

    #[test]
    fn ambient_scoped_socket_supplies_client_config_and_state_dirs() {
        assert_eq!(
            client_dirs_from(
                None,
                None,
                None,
                Path::new("/home/test/.config/flotilla"),
                Path::new("/home/test/.local/state/flotilla"),
                Some(std::ffi::OsStr::new("/work/live-session/config/run/flotilla.sock")),
            )
            .expect("ambient scoped socket forms a complete identity"),
            (PathBuf::from("/work/live-session/config"), PathBuf::from("/work/live-session/state")),
        );
    }

    #[test]
    fn explicit_config_is_not_replaced_by_a_conflicting_scoped_socket() {
        assert_eq!(
            client_dirs_from(
                None,
                Some(Path::new("/work/root-b/config")),
                Some(Path::new("/work/root-b/state")),
                Path::new("/home/test/.config/flotilla"),
                Path::new("/home/test/.local/state/flotilla"),
                Some(std::ffi::OsStr::new("/work/root-a/config/run/flotilla.sock")),
            )
            .expect("paired category overrides form a complete identity"),
            (PathBuf::from("/work/root-b/config"), PathBuf::from("/work/root-b/state")),
        );
    }

    #[test]
    fn daemon_starting_paths_require_config_and_state_overrides_together() {
        let config_only =
            Cli::try_parse_from(["flotilla", "--config-dir", "/work/a/config"]).expect("socket-only commands may parse a config override");
        let state_only =
            Cli::try_parse_from(["flotilla", "--state-dir", "/work/a/state"]).expect("socket-only commands may parse a state override");
        let config_error = config_only.client_paths().expect_err("config-only startup identity must be rejected");
        let state_error = state_only.client_paths().expect_err("state-only startup identity must be rejected");
        assert!(config_error.contains("may start a daemon"), "unexpected error: {config_error}");
        assert!(state_error.contains("may start a daemon"), "unexpected error: {state_error}");
        assert!(Cli::try_parse_from(["flotilla", "--config-dir", "/work/a/config", "--state-dir", "/work/a/state", "status",])
            .expect("paired overrides should parse")
            .client_paths()
            .is_ok());
    }

    #[test]
    fn daemon_stop_is_a_nested_daemon_command() {
        let cli = Cli::try_parse_from(["flotilla", "daemon", "stop"]).expect("daemon stop should parse");
        assert!(matches!(cli.command, Some(SubCommand::Daemon(DaemonArgs { command: Some(DaemonSubCommand::Stop), .. }))));

        let foreground = Cli::try_parse_from(["flotilla", "daemon", "--timeout", "0"]).expect("foreground daemon should still parse");
        assert!(matches!(foreground.command, Some(SubCommand::Daemon(DaemonArgs { command: None, timeout: 0 }))));

        let dev_mode = Cli::try_parse_from(["flotilla", "daemon", "dev-mode", "enable"]).expect("daemon dev-mode enable should parse");
        assert!(matches!(
            dev_mode.command,
            Some(SubCommand::Daemon(DaemonArgs { command: Some(DaemonSubCommand::DevMode { command: DevModeSubCommand::Enable }), .. }))
        ));

        let fleet_mode = Cli::try_parse_from(["flotilla", "daemon", "dev-mode", "disable"]).expect("daemon dev-mode disable should parse");
        assert!(matches!(
            fleet_mode.command,
            Some(SubCommand::Daemon(DaemonArgs { command: Some(DaemonSubCommand::DevMode { command: DevModeSubCommand::Disable }), .. }))
        ));
    }

    #[test]
    fn custom_roots_select_distinct_daemon_stores_and_lifecycle_locks() {
        let paths_a =
            daemon_paths_from(Some(Path::new("/work/a")), None, None, None, Path::new("/default/config"), Path::new("/default/state"))
                .expect("root A forms a complete identity");
        let paths_b =
            daemon_paths_from(Some(Path::new("/work/b")), None, None, None, Path::new("/default/config"), Path::new("/default/state"))
                .expect("root B forms a complete identity");

        assert_eq!(paths_a.config_dir, Path::new("/work/a/config"));
        assert_eq!(paths_a.state_dir, Path::new("/work/a/state"));
        assert_eq!(paths_a.socket_path, Path::new("/work/a/config/run/flotilla.sock"));
        assert_ne!(paths_a.state_dir.join("resources.sqlite"), paths_b.state_dir.join("resources.sqlite"));
        assert_ne!(
            paths_a.state_dir.join(flotilla_core::DAEMON_LIFECYCLE_LOCK_FILE),
            paths_b.state_dir.join(flotilla_core::DAEMON_LIFECYCLE_LOCK_FILE),
        );
    }

    #[test]
    fn root_selector_conflicts_with_category_overrides() {
        assert!(Cli::try_parse_from([
            "flotilla",
            "--root",
            "/work/a",
            "--config-dir",
            "/work/b/config",
            "--state-dir",
            "/work/b/state",
            "status",
        ])
        .is_err());
    }

    #[test]
    fn cli_parses_internal_transient_attach_target() {
        let cli = Cli::try_parse_from(["flotilla", "attach", "--transient", "--host", "feta", "terminal-scratch"])
            .expect("transient attach cli should parse");
        assert!(matches!(
            cli.command,
            Some(SubCommand::Attach(AttachArgs { reference, watch: false, strict: false, take: false, transient: true, host: Some(host) }))
                if reference == "terminal-scratch" && host == "feta"
        ));
    }

    #[test]
    fn cli_parses_host_qualified_materialize_recipe() {
        let cli = Cli::try_parse_from(["flotilla", "attach", "--host", "feta", "terminal-scratch"])
            .expect("host-qualified attach cli should parse");
        assert!(matches!(
            cli.command,
            Some(SubCommand::Attach(AttachArgs { reference, watch: false, strict: false, take: false, transient: false, host: Some(host) }))
                if reference == "terminal-scratch" && host == "feta"
        ));
    }

    #[test]
    fn cli_parses_repo_noun() {
        let cli = Cli::try_parse_from(["flotilla", "repo", "owner/repo"]).expect("repo cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Repo(_)))));
    }

    #[test]
    fn cli_parses_bare_list_nouns_with_json_output() {
        for noun in ["repo", "checkout", "cr", "issue", "agent"] {
            let cli = Cli::try_parse_from(["flotilla", noun, "--json"]).expect("bare noun should parse");
            assert!(cli.json, "{noun} must keep the global JSON flag");
            assert!(cli.command.is_some());
        }
    }

    #[test]
    fn cli_parses_checkout_noun() {
        let cli = Cli::try_parse_from(["flotilla", "checkout", "my-feature", "remove"]).expect("checkout cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Checkout(_)))));
    }

    #[test]
    fn cli_parses_convoy_noun() {
        let cli =
            Cli::try_parse_from(["flotilla", "convoy", "convoy-a", "work", "implement", "complete"]).expect("convoy cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Convoy(_)))));
    }

    #[test]
    fn cli_parses_crew_list_and_handoff_grammar() {
        let list = Cli::try_parse_from(["flotilla", "crew", "list"]).expect("crew list should parse");
        assert!(matches!(list.command, Some(SubCommand::Domain(DomainCommand::Crew(_)))));

        let handoff = Cli::try_parse_from(["flotilla", "crew", "reviewer", "handoff", "--message", "Review commit abc123"])
            .expect("crew handoff should parse");
        assert!(matches!(handoff.command, Some(SubCommand::Domain(DomainCommand::Crew(_)))));

        let marked = Cli::try_parse_from(["flotilla", "crew", "@list", "handoff", "--message", "Review commit abc123"])
            .expect("marked crew role should parse");
        assert!(matches!(marked.command, Some(SubCommand::Domain(DomainCommand::Crew(_)))));

        let literal = Cli::try_parse_from(["flotilla", "crew", "--subject", "@reviewer", "handoff", "--message", "Review commit abc123"])
            .expect("literal crew role should parse");
        assert!(matches!(literal.command, Some(SubCommand::Domain(DomainCommand::Crew(_)))));
    }

    #[test]
    fn artifact_cli_parses_typed_summary_without_a_producer_option() {
        let cli = Cli::try_parse_from([
            "flotilla",
            "artifact",
            "put",
            "--kind",
            "review-round",
            "--about",
            "head-1",
            "--summary",
            "approved=true",
            "round.md",
        ])
        .expect("artifact put parses");
        assert!(matches!(
            cli.command,
            Some(SubCommand::Artifact { command: ArtifactSubCommand::Put { summary, .. } })
                if summary == vec![("approved".to_string(), serde_json::json!(true))]
        ));
        let ledger = Cli::try_parse_from(["flotilla", "artifact", "put", "--kind", "decision-ledger", "ledger.md"])
            .expect("ledger put parses without an explicit subject");
        assert!(matches!(ledger.command, Some(SubCommand::Artifact { command: ArtifactSubCommand::Put { about: None, .. } })));
        assert!(Cli::try_parse_from([
            "flotilla",
            "artifact",
            "put",
            "--kind",
            "brief",
            "--about",
            "convoy",
            "--producer",
            "reviewer",
            "brief.md"
        ])
        .is_err());
    }

    // Help content must match the preserved snapshot with either LF or Windows-checkout CRLF endings.
    #[test]
    fn artifact_put_help_snapshot() {
        let help = Cli::try_parse_from(["flotilla", "artifact", "put", "--help"]).err().expect("help exits parsing").to_string();
        let normalized = help.lines().map(str::trim_end).collect::<Vec<_>>().join("\n") + "\n";
        assert_eq!(normalized, include_str!("snapshots/artifact_put_help.txt").replace("\r\n", "\n"));
    }

    #[test]
    fn cli_parses_cr_noun() {
        let cli = Cli::try_parse_from(["flotilla", "cr", "42", "open"]).expect("cr cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Cr(_)))));
    }

    #[test]
    fn cli_parses_pr_alias() {
        let cli = Cli::try_parse_from(["flotilla", "pr", "42", "open"]).expect("pr alias should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Cr(_)))));
    }

    #[test]
    fn cli_parses_issue_noun() {
        let cli = Cli::try_parse_from(["flotilla", "issue", "1", "open"]).expect("issue cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Issue(_)))));
    }

    // Retired personal-workspace surfaces must be rejected.
    #[test]
    fn cli_rejects_retired_workspace_surfaces() {
        for args in [
            vec!["flotilla", "workspace"],
            vec!["flotilla", "workspace", "ws", "select"],
            vec!["flotilla", "repo", "repo", "prepare-terminal", "/tmp/wt"],
            vec!["flotilla", "agent", "agent", "teleport"],
        ] {
            assert!(Cli::try_parse_from(args).is_err());
        }
    }

    #[test]
    fn cli_parses_agent_noun() {
        let cli = Cli::try_parse_from(["flotilla", "agent", "claude-1", "archive"]).expect("agent cli should parse");
        let Some(SubCommand::Domain(DomainCommand::Agent(noun))) = cli.command else { panic!("expected agent command") };
        assert!(matches!(noun.verb, Some(flotilla_commands::commands::agent::AgentVerb::Archive)));
    }

    #[test]
    fn cli_parses_workflow_template_noun() {
        let cli = Cli::try_parse_from(["flotilla", "workflow-template", "scratch", "apply", "--file", "/tmp/x.yaml"])
            .expect("workflow-template cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::WorkflowTemplate(_)))));
    }

    #[test]
    fn cli_parses_project_noun() {
        let cli = Cli::try_parse_from(["flotilla", "project", "add", "https://example.com/repo.git", "--name", "my-project"])
            .expect("project cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Project(_)))));
    }

    #[test]
    fn cli_parses_convoy_create() {
        let cli = Cli::try_parse_from(["flotilla", "convoy", "my-convoy", "create", "--template", "scratch", "--input", "topic=hi"])
            .expect("convoy create cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Convoy(_)))));
    }

    #[test]
    fn cli_parses_dispatch_queue_with_json() {
        let cli = Cli::try_parse_from(["flotilla", "--json", "dispatch", "queue"]).expect("dispatch queue should parse");
        assert!(cli.json);
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Dispatch(_)))));
    }

    #[test]
    fn cli_parses_host_noun() {
        let cli = Cli::try_parse_from(["flotilla", "host", "list"]).expect("host list should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Host(_)))));
    }

    #[test]
    fn cli_parses_fleet_health_dashboard() {
        let cli = Cli::try_parse_from(["flotilla", "fleet"]).expect("fleet should parse");
        assert!(matches!(cli.command, Some(SubCommand::Fleet { command: None })));
    }

    // Glue: the standalone local pruning command accepts installer arguments,
    // including a negative K so the pruning module emits its recovery error.
    #[test]
    fn cli_parses_generation_pruning() {
        let cli = Cli::try_parse_from(["flotilla", "fleet", "prune", "--fleet-root", "/fleet", "--keep-others", "-1", "--dry-run"])
            .expect("prune parses");
        assert!(
            matches!(cli.command, Some(SubCommand::Fleet { command: Some(super::FleetSubCommand::Prune { fleet_root, keep_others, dry_run: true }) }) if fleet_root == Path::new("/fleet") && keep_others == "-1")
        );
    }

    #[test]
    fn cli_parses_incoming_generation_post_install() {
        // Incoming CLI owns this step; the preceding generation need not parse it.
        let cli = Cli::try_parse_from([
            "flotilla",
            "--json",
            "fleet",
            "post-install",
            "--cleat-bin",
            "/incoming/bin/cleat",
            "--generation",
            "new-gen",
            "--diagnostics-dir",
            "/fleet/diagnostics",
        ])
        .expect("post-install parses");
        assert!(matches!(cli.command, Some(SubCommand::Fleet { command: Some(super::FleetSubCommand::PostInstall { .. }) })));
    }

    #[test]
    fn cli_parses_environment_noun() {
        let cli = Cli::try_parse_from(["flotilla", "environment", "host:alpha", "refresh"]).expect("environment cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Environment(_)))));
    }

    #[test]
    fn cli_parses_env_alias() {
        let cli = Cli::try_parse_from(["flotilla", "env", "prov:builder-1", "refresh"]).expect("env alias should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Environment(_)))));
    }

    #[test]
    fn cli_parses_host_status_with_json() {
        let cli = Cli::try_parse_from(["flotilla", "host", "alpha", "status", "--json"]).expect("host status json should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Host(_)))));
        assert!(cli.json);
    }

    #[test]
    fn cli_global_json_before_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "--json", "topology"]).expect("json before subcommand should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology(TopologyArgs { dot: false }))));
        assert!(cli.json);
    }

    #[test]
    fn cli_repo_context_flag() {
        let cli = Cli::try_parse_from(["flotilla", "--repo", "owner/repo", "checkout", "create", "--branch", "feat-x"])
            .expect("repo context should parse");
        assert!(matches!(cli.command, Some(SubCommand::Domain(DomainCommand::Checkout(_)))));
        assert_eq!(cli.repo.as_deref(), Some("owner/repo"));
    }

    #[test]
    fn cli_no_subcommand_is_none() {
        let cli = Cli::try_parse_from(["flotilla"]).expect("bare cli should parse");
        assert!(cli.command.is_none());
    }
}
