[package]
name = "flotilla-transport"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
flotilla-protocol = { path = "../flotilla-protocol" }
tokio = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true

# Keep native library features stable across build and test commands.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
flotilla-build-features = { path = "../flotilla-build-features" }
flotilla-build-features-async = { path = "../flotilla-build-features-async" }
flotilla-build-features-base = { path = "../flotilla-build-features-base" }
flotilla-build-features-os = { path = "../flotilla-build-features-os" }
flotilla-build-features-tracing = { path = "../flotilla-build-features-tracing" }
flotilla-build-features-types = { path = "../flotilla-build-features-types" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
