apiVersion: flotilla.work/v1
kind: CrewImageBaseline
metadata:
  name: fleet-crew
  namespace: flotilla
spec:
  image: forgejo.lab.flotilla.work/image-builder/flotilla-crew:2026-09-26.22f6464c.596fd32a
