apiVersion: flotilla.work/v1
kind: CrewImageBaseline
metadata:
  name: fleet-crew
  namespace: flotilla
spec:
  image: forgejo.lab.flotilla.work/image-builder/flotilla-crew:2026-09-25.3ef70855.cfce0cb5
