#!/usr/bin/env python3
"""Render the compatibility Dockerfile or pinned fleet ImageLayer definitions.

No registry, forge CI, or third-party Python dependencies are required.
"""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INPUTS = ROOT / '.flotilla/image-layers/inputs.json'


def dockerfile(display=False):
    catalogue = json.loads(INPUTS.read_text())
    parent = catalogue['base_default']
    parts = ['# Generated by ci/crew-image/compose.py; edit image-layers fragments.\n']
    for layer in catalogue['layers']:
        if layer['stage'] == 'capability' and not display:
            continue
        fragment = (ROOT / layer['fragment']).read_text()
        # Substitute the parent only in FROM instructions. Preserve ARGs and
        # helpers: each fragment is also independently buildable by Buildx.
        fragment = re.sub(r'(?m)^FROM \$\{BASE\}(.*)$',
                          lambda m: 'FROM ' + parent + m[1], fragment)
        lines = fragment.splitlines()
        last = max(i for i, line in enumerate(lines) if line.startswith('FROM '))
        lines[last] += ' AS ' + layer['name']
        parts.append('\n'.join(lines) + '\n')
        parent = layer['name']
    return '\n'.join(parts)


def manifests(revision, base):
    if not re.fullmatch(r'[0-9a-f]{40}|[0-9a-f]{64}', revision):
        raise ValueError('revision must be a full lowercase commit ID')
    if not re.fullmatch(r'.*@sha256:[0-9a-f]{64}|sha256:[0-9a-f]{64}', base):
        raise ValueError('base must be a resolved sha256 image digest')
    catalogue = json.loads(INPUTS.read_text())
    rust = re.search(r'^channel = \"([0-9.]+)\"$', (ROOT / 'rust-toolchain.toml').read_text(), re.M).group(1)
    records = []
    for layer in catalogue['layers']:
        stage = layer['stage']
        if stage == 'base':
            provide = 'toolchain:rust@' + rust
            layer.setdefault('provides', []).append(provide)
            layer.setdefault('probes', {})[provide] = ['sh', '-c', 'test \"$(rustc --version | cut -d \" \" -f2)\" = ' + rust]
        parent = ({'kind': 'image', 'value': base} if stage == 'base' else
                  {'kind': 'layer', 'value': 'spine-base'} if stage == 'utilities' else
                  {'kind': 'rebasable'})
        records.append({'apiVersion': 'flotilla.work/v1', 'kind': 'ImageLayer',
                        'metadata': {'namespace': 'flotilla', 'name': layer['name']},
                        'spec': {'stage': stage, 'parent': parent,
                                 'repository': catalogue['repository'], 'revision': revision,
                                 'fragment': layer['fragment'], 'pins': layer.get('pins', {}),
                                 'provides': layer.get('provides', []),
                                 'probes': layer.get('probes', {}),
                                 'input_stability': catalogue['input_stability']}})
    # JSON documents are valid YAML; the operational loader accepts documents.
    return '\n---\n'.join(json.dumps(record, indent=2) for record in records) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--display', action='store_true')
    parser.add_argument('--revision')
    parser.add_argument('--base')
    args = parser.parse_args()
    if args.revision or args.base:
        if not (args.revision and args.base):
            parser.error('--revision and --base are required together')
        print(manifests(args.revision, args.base), end='')
    else:
        print(dockerfile(args.display), end='')
