use std::{
    future::Future,
    path::{Path, PathBuf},
    process::ExitStatus,
    sync::{Arc, OnceLock},
    time::Duration,
};

use clap::Parser;
use color_eyre::Result;
use flotilla_core::{
    agents,
    config::ConfigStore,
    daemon::DaemonHandle,
    path_context::{DaemonHostPath, ExecutionEnvironmentPath},
    path_policy::PathPolicy,
    providers::{
        vcs::{git::GitVcs, Vcs},
        ProcessCommandRunner,
    },
};
use flotilla_protocol::{
    commands::CommandValue, output::OutputFormat, AgentHookEvent, AttachableId, Command, CommandAction, EnvironmentId, HostName,
    ProjectListResponse, RepoIdentity, RepoInfo, RepoSelector, ViewAddress,
};
use flotilla_tui::{app, event_log, theme};
use tracing::info;

/// Flotilla: TUI dashboard for managing development workspaces
#[derive(Parser)]
#[command(version, long_version = binary_version())]
struct Cli {
    /// Git repo roots (repeatable; auto-detected from cwd if omitted)
    #[arg(long)]
    repo_root: Vec<PathBuf>,

    /// Config directory
    #[arg(long)]
    config_dir: Option<PathBuf>,

    /// Socket path (default: ${config_dir}/run/flotilla.sock)
    #[arg(long)]
    socket: Option<PathBuf>,

    /// Theme name (catppuccin-mocha, classic)
    #[arg(long)]
    theme: Option<String>,

    /// Output as JSON instead of human-readable text
    #[arg(long, global = true)]
    json: bool,

    /// Repo context for commands that need it (slug, path, or name)
    #[arg(long)]
    repo: Option<String>,

    #[command(subcommand)]
    command: Option<SubCommand>,
}

fn binary_version() -> &'static str {
    static VERSION: OnceLock<String> = OnceLock::new();
    VERSION.get_or_init(|| format!("{} (wire={})", env!("CARGO_PKG_VERSION"), flotilla_client::BUILD_ID))
}

#[derive(clap::Subcommand)]
enum SubCommand {
    /// Run the daemon server
    Daemon {
        /// Idle timeout in seconds (0 = no timeout)
        #[arg(long, default_value = "300")]
        timeout: u64,
    },
    /// Open the TUI scoped to one View (e.g. `flotilla view convoys/flotilla`).
    ///
    /// Scoped mode shows exactly that View: no tab bar, and the persisted
    /// open-view set is untouched. This is the deep-link entry Presentation
    /// Manager recipes embed (ADR 0013).
    View {
        /// View address: `overview`, `repo/<authority>/<path>`, `convoys/<namespace>`, ...
        /// A `flotilla://` prefix is accepted.
        address: String,
    },
    /// Print repo list and state
    Status,
    /// Stream daemon events to stdout
    Watch,
    /// Show the daemon's current multi-host routing view
    Topology,
    /// Read structured daemon logs from this host or a peer
    Logs {
        /// Peer host name; omit to read this host
        #[arg(long)]
        host: Option<String>,
        /// Only show records this old or newer (for example `2h` or `30m`)
        #[arg(long, value_parser = parse_log_duration)]
        since: Option<Duration>,
        /// Minimum level: trace, debug, info, warn, or error
        #[arg(long, value_parser = ["trace", "debug", "info", "warn", "error"])]
        level: Option<String>,
        /// Exact tracing module target and its children
        #[arg(long)]
        target: Option<String>,
    },
    /// Show fleet-wide host health without collapsing independent observations
    Fleet,
    /// List convoy vessels and crew sessions
    Ls,
    /// Attach to a running convoy crew session
    Attach {
        /// Refuse when another attachment holds the controller seat
        #[arg(long, conflicts_with = "take")]
        strict: bool,
        /// Take control and demote the current controller to watcher
        #[arg(long, conflicts_with = "strict")]
        take: bool,
        /// Convoy, vessel, role, terminal session, or unique prefix
        reference: String,
        /// Internal attach mode used by temporary TUI excursions.
        #[arg(long, hide = true)]
        transient: bool,
        /// Restrict internal attach resolution to the daemon owning this row.
        #[arg(long, hide = true)]
        host: Option<String>,
    },
    /// Emit this host's store-backed fleet replica snapshot
    #[command(hide = true)]
    ReplicaSnapshot,
    /// Receive agent hook events (called by agent hook systems)
    Hook {
        /// Agent harness name (e.g. claude-code, codex, gemini)
        harness: String,
        /// Event type (e.g. session-start, stop, notification)
        event_type: String,
    },
    /// Install or uninstall agent hook configuration
    Hooks {
        #[command(subcommand)]
        command: HooksSubCommand,
    },
    /// Presentation-manager integration
    Pm {
        #[command(subcommand)]
        command: PmSubCommand,
    },
    /// Inspect raw daemon resources
    Resource {
        #[command(subcommand)]
        command: ResourceSubCommand,
    },

    // --- Domain nouns (generated by flotilla-commands) ---
    /// Manage repositories
    Repo(flotilla_commands::commands::repo::RepoNoun),
    /// Manage environments
    Environment(flotilla_commands::commands::environment::EnvironmentNoun),
    /// Manage checkouts
    Checkout(flotilla_commands::commands::checkout::CheckoutNoun),
    /// Manage convoys
    Convoy(flotilla_commands::commands::convoy::ConvoyNoun),
    /// Communicate with crew members
    Crew(flotilla_commands::commands::crew::CrewNoun),
    /// Code review (alias on CrNoun itself, not duplicated here)
    Cr(flotilla_commands::commands::cr::CrNoun),
    /// Issues
    Issue(flotilla_commands::commands::issue::IssueNoun),
    /// Cloud agents
    Agent(flotilla_commands::commands::agent::AgentNoun),
    /// Workspaces
    Workspace(flotilla_commands::commands::workspace::WorkspaceNoun),
    /// Manage and route to hosts
    Host(flotilla_commands::commands::host::HostNounPartial),
    /// Manage workflow templates
    WorkflowTemplate(flotilla_commands::commands::workflow_template::WorkflowTemplateNoun),
    /// Manage projects
    Project(flotilla_commands::commands::project::ProjectNoun),

    /// Generate completions (hidden, called by shell scripts)
    #[command(hide = true)]
    Complete {
        /// The input line to complete
        line: String,
        /// Cursor position within the line
        #[arg(default_value = "0")]
        cursor_pos: usize,
    },
    /// Output shell completion setup scripts
    Completions {
        /// Shell type
        #[arg(value_enum)]
        shell: CompletionShell,
    },
}

#[derive(Clone, clap::ValueEnum)]
enum CompletionShell {
    Bash,
    Zsh,
    Fish,
}

#[derive(clap::Subcommand)]
enum PmSubCommand {
    /// Run the manifest metadata-patch connector for the enclosing PM
    Connect {
        /// Zellij binary for pipe delivery (default: $ZELLIJ_BIN, then `zellij`)
        #[arg(long)]
        zellij_bin: Option<String>,
        /// Restrict pipe delivery to one plugin instance
        #[arg(long)]
        plugin_url: Option<String>,
        /// Publish to a wheelhouse unix socket instead of zellij pipes
        #[arg(long)]
        wheelhouse_socket: Option<PathBuf>,
        /// Binary name minted into materialise recipes the PM executes
        #[arg(long, default_value = "flotilla")]
        flotilla_bin: String,
    },
}

#[derive(clap::Subcommand)]
enum HooksSubCommand {
    /// Install hooks for an agent harness
    Install {
        /// Agent harness (e.g. claude-code)
        harness: String,
        /// Install to user settings (~/.claude/settings.json)
        #[arg(long)]
        user: bool,
        /// Install to project settings (.claude/settings.json, committed)
        #[arg(long)]
        project: bool,
        /// Install to local project settings (.claude/settings.local.json, gitignored)
        #[arg(long)]
        local: bool,
        /// Show plugin marketplace install instructions instead
        #[arg(long)]
        plugin: bool,
    },
    /// Remove hooks for an agent harness
    Uninstall {
        /// Agent harness (e.g. claude-code)
        harness: String,
        /// Remove from user settings
        #[arg(long)]
        user: bool,
        /// Remove from project settings
        #[arg(long)]
        project: bool,
        /// Remove from local project settings
        #[arg(long)]
        local: bool,
    },
}

#[derive(clap::Subcommand)]
enum ResourceSubCommand {
    /// List resources of a kind
    List(ResourceListArgs),
    /// Create or update a raw resource document
    Apply(ResourceApplyArgs),
    /// Get one resource by name
    Get(ResourceGetArgs),
    /// Delete exactly one raw resource object, bypassing lifecycle gates
    Delete(ResourceDeleteArgs),
    /// Watch resources of a kind
    Watch(ResourceWatchArgs),
}

#[derive(clap::Args, bon::Builder)]
struct ResourceListArgs {
    /// Resource kind or plural name, e.g. convoys or WorkflowTemplate
    kind: String,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    namespace: String,
    /// Route the query to a peer host
    #[arg(long)]
    host: Option<String>,
    /// Include read-only replicas from peer roots
    #[arg(long)]
    include_replicas: bool,
}

#[derive(clap::Args)]
struct ResourceGetArgs {
    /// Resource kind or plural name, e.g. convoys or WorkflowTemplate
    kind: String,
    /// Resource name
    name: String,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    namespace: String,
    /// Route the query to a peer host
    #[arg(long)]
    host: Option<String>,
}

#[derive(clap::Args, bon::Builder)]
struct ResourceWatchArgs {
    /// Resource kind or plural name, e.g. convoys or WorkflowTemplate
    kind: String,
    /// Restrict the stream to one resource name
    name: Option<String>,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    namespace: String,
    /// Route the watch to a peer host
    #[arg(long)]
    host: Option<String>,
    /// Include read-only replicas from peer roots
    #[arg(long)]
    include_replicas: bool,
    /// Resume strictly after a cursor emitted by an earlier read or watch
    #[arg(long)]
    from_cursor: Option<flotilla_protocol::ResourceCursor>,
}

#[derive(clap::Args)]
struct ResourceDeleteArgs {
    /// Exact resource kind or plural name
    kind: String,
    /// Exact resource name
    name: String,
    /// Resource namespace
    #[arg(long, default_value = "flotilla")]
    namespace: String,
}

#[derive(clap::Args)]
struct ResourceApplyArgs {
    /// Resource document path (JSON or YAML)
    #[arg(short, long)]
    file: PathBuf,
    /// Default namespace when metadata.namespace is omitted
    #[arg(long, default_value = "flotilla")]
    namespace: String,
    /// Route the mutation to a peer host
    #[arg(long)]
    host: Option<String>,
}

impl Cli {
    fn config_dir(&self) -> PathBuf {
        self.config_dir.clone().unwrap_or_else(|| PathPolicy::from_process_env().config_dir.into_path_buf())
    }

    fn socket_path(&self) -> PathBuf {
        socket_path_from(self.socket.as_deref(), &self.config_dir(), std::env::var_os("FLOTILLA_DAEMON_SOCKET").as_deref())
    }
}

fn socket_path_from(explicit: Option<&Path>, config_dir: &Path, environment: Option<&std::ffi::OsStr>) -> PathBuf {
    environment.map(PathBuf::from).or_else(|| explicit.map(PathBuf::from)).unwrap_or_else(|| config_dir.join("run/flotilla.sock"))
}

fn host_daemon_socket_required(contained_marker: Option<&std::ffi::OsStr>) -> bool {
    contained_marker.is_some()
}

async fn connect_cli_socket(
    socket_path: &Path,
    config_dir: &Path,
    state_dir: &Path,
    config_dir_override: Option<&Path>,
    socket_override: Option<&Path>,
    require_host_daemon: bool,
) -> Result<Arc<flotilla_tui::socket::SocketDaemon>, String> {
    if require_host_daemon {
        flotilla_tui::socket::connect_required_host_daemon(socket_path).await
    } else {
        flotilla_tui::socket::connect_or_spawn(socket_path, config_dir, state_dir, config_dir_override, socket_override).await
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    flotilla_core::tls::install_default_provider();
    color_eyre::install()?;
    let mut cli = Cli::try_parse().unwrap_or_else(|error| exit_cli_parse_error(error));
    let format = OutputFormat::from_json_flag(cli.json);
    let command = cli.command.take();

    let result = match command {
        Some(SubCommand::View { address }) => {
            // Parse before touching the terminal so a bad address in a
            // recipe fails loudly at the shell (ADR 0013).
            let address: flotilla_protocol::ViewAddress = match address.parse() {
                Ok(address) => address,
                Err(e) => {
                    eprintln!("Error: {e}");
                    std::process::exit(2);
                }
            };
            run_tui(cli, Some(address)).await
        }
        Some(SubCommand::Daemon { timeout }) => run_daemon(&cli, timeout).await,
        Some(SubCommand::Status) => run_status(&cli, format).await,
        Some(SubCommand::Watch) => run_watch(&cli, format).await,
        Some(SubCommand::Topology) => run_topology_command(&cli, format).await,
        Some(SubCommand::Logs { host, since, level, target }) => run_logs(&cli, host.as_deref(), since, level, target).await,
        Some(SubCommand::Fleet) => run_fleet_health(&cli, format).await,
        Some(SubCommand::Ls) => run_fleet_list(&cli, format).await,
        Some(SubCommand::Attach { reference, strict, take, transient, host }) => {
            run_attach(&cli, &reference, attach_mode(strict, take), transient, host.as_deref(), format).await
        }
        Some(SubCommand::ReplicaSnapshot) => run_replica_snapshot(&cli).await,
        Some(SubCommand::Hook { harness, event_type }) => run_hook(&cli, &harness, &event_type).await,
        Some(SubCommand::Hooks { command }) => run_hooks_command(&command).await,
        Some(SubCommand::Pm { command }) => run_pm_command(&cli, command).await,
        Some(SubCommand::Resource { command }) => run_resource_command(&cli, command, format).await,

        Some(SubCommand::Repo(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Environment(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Checkout(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Convoy(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Crew(noun)) => {
            let crew_id = std::env::var("FLOTILLA_CREW_ID").ok();
            dispatch(noun.resolve_with_crew_id(crew_id).map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await
        }
        Some(SubCommand::Cr(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Issue(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Agent(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Workspace(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Host(partial)) => {
            use flotilla_commands::Refinable;
            dispatch(partial.refine().and_then(|n| n.resolve()).map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await
        }
        Some(SubCommand::WorkflowTemplate(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,
        Some(SubCommand::Project(noun)) => dispatch(noun.resolve().map_err(|e| color_eyre::eyre::eyre!(e))?, &cli, format).await,

        Some(SubCommand::Complete { line, cursor_pos }) => {
            run_complete(&line, cursor_pos);
            Ok(())
        }
        Some(SubCommand::Completions { shell }) => {
            run_completions(shell);
            Ok(())
        }

        None => run_tui(cli, None).await,
    };

    if let Err(error) = &result {
        let message = format!("{error:?}");
        let already_reexecuted = std::env::var(flotilla_tui::socket::reconnect::REEXEC_BUILD_ENV).ok();
        if should_reexec_for_incompatible_daemon(&message, already_reexecuted.as_deref()) {
            std::env::set_var(flotilla_tui::socket::reconnect::REEXEC_BUILD_ENV, flotilla_tui::socket::BUILD_ID);
            reexec_current_process()?;
        }
    }
    result
}

fn should_reexec_for_incompatible_daemon(error: &str, already_reexecuted_build: Option<&str>) -> bool {
    flotilla_tui::socket::reconnect::is_incompatible_daemon_error(error) && already_reexecuted_build != Some(flotilla_tui::socket::BUILD_ID)
}

fn reexec_current_process() -> Result<()> {
    let executable = std::env::current_exe()?;
    let mut command = std::process::Command::new(executable);
    command.args(std::env::args_os().skip(1));
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        let error = command.exec();
        Err(error.into())
    }
    #[cfg(not(unix))]
    {
        command.spawn()?;
        std::process::exit(0);
    }
}

fn exit_cli_parse_error(error: clap::Error) -> ! {
    let hint = flotilla_commands::subject_parse_hint(&error);
    let exit_code = error.exit_code();
    if let Err(print_error) = error.print() {
        eprintln!("failed to print command-line error: {print_error}");
    }
    if let Some(hint) = hint {
        eprintln!("\n{hint}");
    }
    std::process::exit(exit_code)
}

fn select_startup_repo_roots(cli_roots: &[PathBuf], cwd_repo_root: Option<PathBuf>) -> Vec<PathBuf> {
    if cli_roots.is_empty() {
        cwd_repo_root.into_iter().collect()
    } else {
        let mut roots = Vec::with_capacity(cli_roots.len());
        for root in cli_roots {
            let canonical = std::fs::canonicalize(root).unwrap_or_else(|_| root.clone());
            if !roots.contains(&canonical) {
                roots.push(canonical);
            }
        }
        roots
    }
}

async fn startup_repo_roots(cli_roots: &[PathBuf]) -> Vec<PathBuf> {
    let cwd_repo_root = if cli_roots.is_empty() {
        let cwd = std::env::current_dir().ok().map(ExecutionEnvironmentPath::new);
        let vcs = GitVcs::new(Arc::new(ProcessCommandRunner));
        match cwd {
            Some(cwd) => vcs.resolve_repo_root(&cwd).await.map(ExecutionEnvironmentPath::into_path_buf),
            None => None,
        }
    } else {
        None
    };
    select_startup_repo_roots(cli_roots, cwd_repo_root)
}

async fn show_startup_splash<F, Fut>(scoped_view: Option<&flotilla_protocol::ViewAddress>, show_splash: F) -> Result<()>
where
    F: FnOnce() -> Fut,
    Fut: Future<Output = Result<()>>,
{
    if scoped_view.is_none() {
        show_splash().await?;
    }
    Ok(())
}

fn default_project_landing(
    repos: &[RepoInfo],
    startup_repo_roots: &[PathBuf],
    projects: &ProjectListResponse,
) -> Option<(RepoIdentity, ViewAddress)> {
    let repo = startup_repo_roots.iter().find_map(|root| {
        let root = std::fs::canonicalize(root).unwrap_or_else(|_| root.clone());
        repos
            .iter()
            .find(|repo| repo.path.as_ref().is_some_and(|path| std::fs::canonicalize(path).unwrap_or_else(|_| path.clone()) == root))
    })?;
    let repository_key = repo.repository_key.as_ref()?;
    let project = projects
        .projects
        .iter()
        .filter(|project| {
            matches!(project.repositories.as_slice(), [repository] if &repository.key == repository_key && repository.subpaths.is_empty())
        })
        .min_by_key(|project| (project.name != repo.name, project.namespace.as_str(), project.name.as_str()))?;
    Some((repo.identity.clone(), project.address.clone()))
}

/// Run the TUI. With `scoped_view`, run in scoped mode: exactly that View,
/// no tab shell, no open-view persistence.
async fn run_tui(cli: Cli, scoped_view: Option<flotilla_protocol::ViewAddress>) -> Result<()> {
    let paths = PathPolicy::from_process_env();
    event_log::init_with_dir(paths.state_dir.as_path());
    let startup = std::time::Instant::now();
    let resolved_config_dir = cli.config_dir();
    let config = Arc::new(ConfigStore::new(DaemonHostPath::new(&resolved_config_dir), paths.state_dir.clone()));

    // Initialize the terminal immediately. Full-app mode shows the splash for
    // fast visual feedback; scoped mode opens directly into its target view.
    let mut terminal = ratatui::init();
    flotilla_tui::terminal::install_panic_hook();
    #[cfg(unix)]
    flotilla_tui::terminal::install_sigterm_handler();

    let startup_repo_roots = startup_repo_roots(&cli.repo_root).await;
    let cli_theme = cli.theme.clone();
    let socket_path = cli.socket_path();
    let config_dir_override = cli.config_dir.clone();
    let socket_override = cli.socket.clone();
    let require_host_daemon =
        host_daemon_socket_required(std::env::var_os(flotilla_core::providers::environment::CONTAINED_DAEMON_REQUIRED_ENV).as_deref());

    // Spawn daemon init on a separate task so full-app startup can run it
    // concurrently with the splash (which uses blocking event polling).
    let daemon_log_path =
        paths.state_dir.as_path().join(flotilla_core::log_file::DAEMON_LOG_DIRECTORY).join(flotilla_core::log_file::DAEMON_LOG_FILE);
    let daemon_panic_log_path = resolved_config_dir.join("daemon-panic.log");
    let initial_socket_path = socket_path.clone();
    let initial_config_dir = resolved_config_dir.clone();
    let initial_state_dir = paths.state_dir.clone();
    let initial_config_override = config_dir_override.clone();
    let initial_socket_override = socket_override.clone();
    let daemon_task = tokio::spawn(async move {
        connect_cli_socket(
            &initial_socket_path,
            &initial_config_dir,
            initial_state_dir.as_path(),
            initial_config_override.as_deref(),
            initial_socket_override.as_deref(),
            require_host_daemon,
        )
        .await
        .map(|d| d as Arc<dyn DaemonHandle>)
    });

    show_startup_splash(scoped_view.as_ref(), || flotilla_tui::splash::show_splash(&mut terminal)).await?;
    let daemon = match daemon_task.await {
        Ok(Ok(daemon)) => {
            std::env::remove_var(flotilla_tui::socket::reconnect::REEXEC_BUILD_ENV);
            info!(elapsed = ?startup.elapsed(), "daemon ready");
            daemon
        }
        Ok(Err(e)) => {
            flotilla_tui::terminal::restore_terminal();
            eprintln!("  Check daemon log at {}", daemon_log_path.display());
            eprintln!("  Check panic log at {}", daemon_panic_log_path.display());
            return Err(color_eyre::eyre::eyre!(e));
        }
        Err(e) => {
            flotilla_tui::terminal::restore_terminal();
            return Err(color_eyre::eyre::eyre!("daemon initialization panicked: {e}"));
        }
    };

    for root in &startup_repo_roots {
        if let Err(e) = daemon
            .execute(flotilla_protocol::Command {
                node_id: None,
                provisioning_target: None,
                context_repo: None,
                action: flotilla_protocol::CommandAction::TrackRepoPath { path: root.clone() },
            })
            .await
        {
            info!(repo = %root.display(), err = %e, "failed to add repo");
        }
    }

    let theme_name = cli_theme.or_else(|| config.load_config().ui.theme.clone()).unwrap_or_else(|| "catppuccin-mocha".to_string());
    let initial_theme = theme::theme_by_name(&theme_name);
    if !initial_theme.name.eq_ignore_ascii_case(&theme_name) {
        tracing::warn!(requested = %theme_name, using = %initial_theme.name, "unknown theme, falling back");
    }

    let pm_connector = flotilla_tui::pm_open::detect_connector();
    let repos_info = daemon.list_repos().await.unwrap_or_default();
    let default_landing = if scoped_view.is_none() && config.load_open_views().is_none() && !startup_repo_roots.is_empty() {
        match daemon
            .execute_query(
                Command { node_id: None, provisioning_target: None, context_repo: None, action: CommandAction::QueryProjectList {} },
                uuid::Uuid::new_v4(),
            )
            .await
        {
            Ok(CommandValue::ProjectList(projects)) => default_project_landing(&repos_info, &startup_repo_roots, &projects),
            Ok(value) => {
                info!(?value, "default project query returned an unexpected result; using repo page");
                None
            }
            Err(error) => {
                info!(%error, "could not resolve default project landing; using repo page");
                None
            }
        }
    } else {
        None
    };
    let mut app = match scoped_view.clone() {
        Some(address) => app::App::new_scoped(daemon.clone(), repos_info, Arc::clone(&config), initial_theme.clone(), address),
        None => app::App::new_with_default_landing(daemon.clone(), repos_info, Arc::clone(&config), initial_theme.clone(), default_landing),
    }
    .with_pm_connector(pm_connector.clone());
    restore_tui_handoff(&mut app);

    loop {
        match flotilla_tui::run::run_event_loop(terminal, app).await? {
            flotilla_tui::run::EventLoopExit::Quit => return Ok(()),
            flotilla_tui::run::EventLoopExit::DaemonDisconnected(disconnected_app) => {
                info!("daemon disconnected; reconnecting TUI");
                app = *disconnected_app;
            }
        }

        terminal = ratatui::init();
        let connected = match flotilla_tui::socket::reconnect::connect_with_retry(
            || {
                connect_cli_socket(
                    &socket_path,
                    &resolved_config_dir,
                    paths.state_dir.as_path(),
                    config_dir_override.as_deref(),
                    socket_override.as_deref(),
                    require_host_daemon,
                )
            },
            |notice| {
                let (attempt, detail) = match notice {
                    flotilla_tui::socket::reconnect::ReconnectNotice::Attempt { attempt } => (attempt, None),
                    flotilla_tui::socket::reconnect::ReconnectNotice::Retry { attempt, error, delay } => {
                        (attempt, Some(format!("{error} — retrying in {:.1}s", delay.as_secs_f64())))
                    }
                };
                if let Err(error) = flotilla_tui::run::render_reconnect_frame(&mut terminal, attempt, detail.as_deref(), &initial_theme) {
                    tracing::warn!(%error, "failed to render daemon reconnect status");
                }
            },
        )
        .await
        {
            Ok(connected) => connected,
            Err(error) => {
                if let Err(handoff_error) = persist_tui_handoff(&app, paths.state_dir.as_path()) {
                    tracing::warn!(error = %handoff_error, "failed to persist TUI state for re-exec");
                }
                flotilla_tui::terminal::restore_terminal();
                return Err(color_eyre::eyre::eyre!(error));
            }
        };
        info!("TUI reconnected to daemon");
        let repos_info = connected.list_repos().await.unwrap_or_default();
        app.reconnect_daemon(connected as Arc<dyn DaemonHandle>, repos_info);
    }
}

const TUI_HANDOFF_ENV: &str = "FLOTILLA_TUI_HANDOFF";

fn persist_tui_handoff(app: &app::App, state_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(state_dir)?;
    let path = state_dir.join(format!("tui-handoff-{}-{}.json", std::process::id(), uuid::Uuid::new_v4()));
    std::fs::write(&path, serde_json::to_vec(&app.handoff())?)?;
    std::env::set_var(TUI_HANDOFF_ENV, &path);
    Ok(())
}

fn restore_tui_handoff(app: &mut app::App) {
    let Some(path) = std::env::var_os(TUI_HANDOFF_ENV).map(PathBuf::from) else { return };
    std::env::remove_var(TUI_HANDOFF_ENV);
    let handoff = std::fs::read(&path)
        .map_err(|error| error.to_string())
        .and_then(|contents| serde_json::from_slice(&contents).map_err(|error| error.to_string()));
    let _ = std::fs::remove_file(&path);
    match handoff {
        Ok(handoff) => {
            app.restore_handoff(handoff);
            app.ui.command_echo = Some("Re-executed and reconnected to daemon".to_string());
        }
        Err(error) => tracing::warn!(%error, path = %path.display(), "could not restore TUI re-exec handoff"),
    }
}

async fn run_daemon(cli: &Cli, timeout_secs: u64) -> Result<()> {
    let daemon_binary = resolve_flotillad_binary()?;
    let mut command = tokio::process::Command::new(&daemon_binary);
    command.arg("--timeout").arg(timeout_secs.to_string());
    if let Some(config_dir) = cli.config_dir.as_ref() {
        command.arg("--config-dir").arg(config_dir);
    }
    if let Some(socket) = cli.socket.as_ref() {
        command.arg("--socket").arg(socket);
    }
    let status = command.status().await?;
    if status.success() {
        Ok(())
    } else {
        Err(color_eyre::eyre::eyre!(
            "flotillad exited with status {}",
            status.code().map(|code| code.to_string()).unwrap_or_else(|| "signal".to_string())
        ))
    }
}

fn resolve_flotillad_binary() -> Result<PathBuf> {
    if let Ok(path) = std::env::var("FLOTILLAD_BIN") {
        return Ok(PathBuf::from(path));
    }

    let current = std::env::current_exe()?;
    let parent = current.parent().ok_or_else(|| color_eyre::eyre::eyre!("current executable has no parent directory"))?;
    let mut candidates = vec![parent.join("flotillad")];
    if parent.file_name().is_some_and(|name| name == "deps") {
        if let Some(grandparent) = parent.parent() {
            candidates.push(grandparent.join("flotillad"));
        }
    }

    candidates
        .into_iter()
        .find(|candidate| candidate.exists())
        .ok_or_else(|| color_eyre::eyre::eyre!("failed to locate flotillad next to {}", current.display()))
}

/// Reset SIGPIPE so piped CLI commands (e.g. `watch | head`) exit cleanly.
/// Only called for CLI subcommands — not the TUI (which needs terminal restore on exit)
/// or the daemon (which shouldn't be killed by a broken stdout pipe).
#[cfg(unix)]
fn reset_sigpipe() {
    // SAFETY: libc::signal is safe to call before I/O begins. Tokio does not configure SIGPIPE.
    unsafe {
        libc::signal(libc::SIGPIPE, libc::SIG_DFL);
    }
}

#[cfg(not(unix))]
fn reset_sigpipe() {}

async fn run_status(cli: &Cli, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    flotilla_tui::cli::run_status(&cli.socket_path(), format).await.map_err(|e| color_eyre::eyre::eyre!(e))
}

async fn run_pm_command(cli: &Cli, command: PmSubCommand) -> Result<()> {
    match command {
        PmSubCommand::Connect { zellij_bin, plugin_url, wheelhouse_socket, flotilla_bin } => {
            let options = flotilla_tui::pm_connect::PmConnectOptions::builder()
                .maybe_zellij_bin(zellij_bin)
                .maybe_plugin_url(plugin_url)
                .maybe_wheelhouse_socket(wheelhouse_socket)
                .flotilla_bin(flotilla_bin)
                .build();
            flotilla_tui::pm_connect::run(
                &cli.socket_path(),
                &cli.config_dir(),
                cli.config_dir.as_deref(),
                cli.socket.as_deref(),
                host_daemon_socket_required(
                    std::env::var_os(flotilla_core::providers::environment::CONTAINED_DAEMON_REQUIRED_ENV).as_deref(),
                ),
                options,
            )
            .await
            .map_err(|e| color_eyre::eyre::eyre!(e))
        }
    }
}

async fn run_watch(cli: &Cli, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    flotilla_tui::cli::run_watch(&cli.socket_path(), format).await.map_err(|e| color_eyre::eyre::eyre!(e))
}

async fn connect_daemon(cli: &Cli) -> Result<Arc<dyn DaemonHandle>> {
    let socket_path = cli.socket_path();
    let config_dir = cli.config_dir();
    let paths = PathPolicy::from_process_env();
    let daemon = connect_cli_socket(
        &socket_path,
        &config_dir,
        paths.state_dir.as_path(),
        cli.config_dir.as_deref(),
        cli.socket.as_deref(),
        host_daemon_socket_required(std::env::var_os(flotilla_core::providers::environment::CONTAINED_DAEMON_REQUIRED_ENV).as_deref()),
    )
    .await
    .map_err(|e| color_eyre::eyre::eyre!(e))?;
    Ok(daemon as Arc<dyn DaemonHandle>)
}

async fn run_control_command(cli: &Cli, command: Command, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    let daemon = connect_daemon(cli).await?;
    let result = match flotilla_tui::cli::run_command(&*daemon, command, format).await {
        Ok(result) => result,
        Err(message) => exit_command_error(message, format),
    };
    if let CommandValue::Error { .. } = result {
        std::process::exit(1);
    }
    if let CommandValue::ConvoyStarted { name, attach_plan: Some(plan), binding } = result {
        if matches!(format, OutputFormat::Human) {
            stamp_pane_identity(&name, binding.as_ref()).await;
            return run_attach_plan(&*daemon, &plan).await;
        }
    }
    Ok(())
}

fn exit_command_error(message: String, format: OutputFormat) -> ! {
    match format {
        OutputFormat::Human => eprintln!("error: {message}"),
        OutputFormat::Json => println!("{}", flotilla_protocol::output::json_pretty(&CommandValue::Error { message })),
    }
    std::process::exit(1);
}

fn attach_mode(strict: bool, take: bool) -> flotilla_protocol::commands::AttachMode {
    match (strict, take) {
        (true, false) => flotilla_protocol::commands::AttachMode::Strict,
        (false, true) => flotilla_protocol::commands::AttachMode::Take,
        (false, false) => flotilla_protocol::commands::AttachMode::Default,
        (true, true) => unreachable!("clap rejects --strict with --take"),
    }
}

async fn run_attach(
    cli: &Cli,
    reference: &str,
    mode: flotilla_protocol::commands::AttachMode,
    transient: bool,
    host: Option<&str>,
    format: OutputFormat,
) -> Result<()> {
    reset_sigpipe();
    let daemon = connect_daemon(cli).await?;
    let result = daemon
        .execute_query(
            Command {
                node_id: None,
                provisioning_target: None,
                context_repo: None,
                action: if transient {
                    CommandAction::AttachTransient {
                        reference: reference.to_string(),
                        host: host.map(flotilla_protocol::HostName::new),
                        mode,
                    }
                } else {
                    CommandAction::Attach { reference: reference.to_string(), host: host.map(flotilla_protocol::HostName::new), mode }
                },
            },
            uuid::Uuid::new_v4(),
        )
        .await
        .map_err(|e| color_eyre::eyre::eyre!(e))?;

    match result {
        CommandValue::AttachCommandResolved { plan, binding } => match format {
            OutputFormat::Json => {
                println!("{}", flotilla_protocol::output::json_pretty(&CommandValue::AttachCommandResolved { plan, binding }));
                Ok(())
            }
            OutputFormat::Human => {
                if !transient {
                    stamp_pane_identity(reference, binding.as_ref()).await;
                }
                run_attach_plan(&*daemon, &plan).await
            }
        },
        CommandValue::Error { message } => match format {
            OutputFormat::Json => {
                println!("{}", flotilla_protocol::output::json_pretty(&CommandValue::Error { message: message.clone() }));
                Err(color_eyre::eyre::eyre!(message))
            }
            OutputFormat::Human => {
                eprintln!("{message}");
                std::process::exit(1);
            }
        },
        other => Err(color_eyre::eyre::eyre!("unexpected attach response: {other:?}")),
    }
}

/// Publish pane ≙ identity into the enclosing PM's metadata plane before
/// launching the attach command — the one moment a process knows the binding
/// (flotilla-org/flotilla#708, half 1). Best-effort: a PM-less or failed
/// stamp never blocks the attach.
async fn stamp_pane_identity(reference: &str, binding: Option<&flotilla_protocol::AttachBinding>) {
    use flotilla_manifest::{pm::PmInstance, stamp::pane_stamp};
    let Some(pm) = PmInstance::detect(&|key| std::env::var(key).ok()) else {
        return;
    };
    let Some(pane) = pm.current_pane() else {
        return;
    };
    if let Err(error) = pm.sink().send(&pane_stamp(pane, reference, binding)).await {
        eprintln!("warning: could not stamp pane identity: {error}");
    }
}

async fn run_fleet_list(cli: &Cli, format: OutputFormat) -> Result<()> {
    run_control_command(
        cli,
        Command { node_id: None, provisioning_target: None, context_repo: None, action: CommandAction::QueryFleetList {} },
        format,
    )
    .await
}

async fn run_fleet_health(cli: &Cli, format: OutputFormat) -> Result<()> {
    run_control_command(
        cli,
        Command { node_id: None, provisioning_target: None, context_repo: None, action: CommandAction::QueryFleetHealth {} },
        format,
    )
    .await
}

async fn run_replica_snapshot(cli: &Cli) -> Result<()> {
    reset_sigpipe();
    let socket_path = cli.socket_path();
    let daemon = flotilla_tui::socket::SocketDaemon::connect(&socket_path)
        .await
        .map_err(|e| color_eyre::eyre::eyre!("cannot connect to daemon at {}: {e}", socket_path.display()))?;
    let result = daemon
        .execute_query(
            Command { node_id: None, provisioning_target: None, context_repo: None, action: CommandAction::QueryFleetReplicaSnapshot {} },
            uuid::Uuid::new_v4(),
        )
        .await
        .map_err(|e| color_eyre::eyre::eyre!(e))?;
    match result {
        CommandValue::FleetReplicaSnapshot(snapshot) => {
            println!("{}", flotilla_protocol::output::json_pretty(&*snapshot));
            Ok(())
        }
        CommandValue::Error { message } => Err(color_eyre::eyre::eyre!(message)),
        other => Err(color_eyre::eyre::eyre!("unexpected replica snapshot response: {other:?}")),
    }
}

async fn run_resource_command(cli: &Cli, command: ResourceSubCommand, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    match command {
        ResourceSubCommand::List(args) => {
            let node_id = resolve_optional_host_node(cli, args.host.as_deref()).await?;
            let daemon = connect_daemon(cli).await?;
            let response = flotilla_client::resource::ResourceClient::new(Arc::clone(&daemon))
                .list(
                    flotilla_client::resource::ResourceListRequest::builder()
                        .kind(args.kind)
                        .namespace(args.namespace)
                        .maybe_node_id(node_id.clone())
                        .include_replicas(args.include_replicas)
                        .build(),
                )
                .await
                .map_err(|e| color_eyre::eyre::eyre!(e))?;
            print_resource_read(daemon.as_ref(), node_id, response, format).await
        }
        ResourceSubCommand::Get(args) => {
            let node_id = resolve_optional_host_node(cli, args.host.as_deref()).await?;
            let daemon = connect_daemon(cli).await?;
            let response = flotilla_client::resource::ResourceClient::new(Arc::clone(&daemon))
                .get(
                    flotilla_client::resource::ResourceGetRequest::builder()
                        .kind(args.kind)
                        .name(args.name)
                        .namespace(args.namespace)
                        .maybe_node_id(node_id.clone())
                        .build(),
                )
                .await
                .map_err(|e| color_eyre::eyre::eyre!(e))?;
            print_resource_read(daemon.as_ref(), node_id, response, format).await
        }
        ResourceSubCommand::Apply(args) => {
            let node_id = resolve_optional_host_node(cli, args.host.as_deref()).await?;
            let raw = std::fs::read_to_string(&args.file)
                .map_err(|error| color_eyre::eyre::eyre!("read resource document {}: {error}", args.file.display()))?;
            let document: serde_json::Value = serde_yml::from_str(&raw)
                .map_err(|error| color_eyre::eyre::eyre!("parse resource document {}: {error}", args.file.display()))?;
            run_control_command(
                cli,
                Command {
                    node_id,
                    provisioning_target: None,
                    context_repo: None,
                    action: CommandAction::ResourceApply { namespace: args.namespace, document },
                },
                format,
            )
            .await
        }
        ResourceSubCommand::Delete(args) => {
            run_control_command(
                cli,
                Command {
                    node_id: None,
                    provisioning_target: None,
                    context_repo: None,
                    action: CommandAction::ResourceDelete { namespace: args.namespace, kind: args.kind, name: args.name },
                },
                format,
            )
            .await
        }
        ResourceSubCommand::Watch(args) => run_resource_watch(cli, args, format).await,
    }
}

async fn resolve_optional_host_node(cli: &Cli, host: Option<&str>) -> Result<Option<flotilla_protocol::NodeId>> {
    match host {
        Some(host) => {
            let (_environment_id, node_id) = resolve_host_target(cli, &HostName::new(host)).await?;
            Ok(Some(node_id))
        }
        None => Ok(None),
    }
}

async fn print_resource_read(
    daemon: &dyn DaemonHandle,
    node_id: Option<flotilla_protocol::NodeId>,
    response: flotilla_protocol::ResourceReadEnvelope,
    format: OutputFormat,
) -> Result<()> {
    let value = serde_json::to_value(response).map_err(|error| color_eyre::eyre::eyre!("encode resource read: {error}"))?;
    println!("{}", format_resource_value(daemon, node_id, value, format).await?);
    Ok(())
}

async fn format_resource_value(
    daemon: &dyn DaemonHandle,
    node_id: Option<flotilla_protocol::NodeId>,
    value: serde_json::Value,
    format: OutputFormat,
) -> Result<String> {
    if format == OutputFormat::Json {
        return Ok(flotilla_protocol::output::json_pretty(&value));
    }
    let hosts = daemon
        .execute_query(
            Command { node_id, provisioning_target: None, context_repo: None, action: CommandAction::QueryHostList {} },
            uuid::Uuid::new_v4(),
        )
        .await;
    Ok(format_human_resource_value(value, hosts))
}

fn format_human_resource_value<E>(mut value: serde_json::Value, hosts: std::result::Result<CommandValue, E>) -> String {
    let Ok(CommandValue::HostList(hosts)) = hosts else {
        return flotilla_protocol::output::json_pretty(&value);
    };
    let names = hosts
        .hosts
        .iter()
        .filter_map(|host| {
            let host_id = host.environment_id.as_ref()?.host_id()?.to_string();
            let display_name = host.node.as_ref().map(|node| node.display_name.clone()).unwrap_or_else(|| host.host_name.to_string());
            Some((host_id, display_name))
        })
        .collect::<std::collections::HashMap<_, _>>();
    replace_host_ids(&mut value, &names);
    flotilla_protocol::output::json_pretty(&value)
}

fn replace_host_ids(value: &mut serde_json::Value, names: &std::collections::HashMap<String, String>) {
    match value {
        serde_json::Value::String(text) => {
            if let Some(display_name) = names.get(text) {
                *text = display_name.clone();
            }
        }
        serde_json::Value::Array(values) => {
            for value in values {
                replace_host_ids(value, names);
            }
        }
        serde_json::Value::Object(fields) => {
            for value in fields.values_mut() {
                replace_host_ids(value, names);
            }
        }
        _ => {}
    }
}

async fn run_resource_watch(cli: &Cli, args: ResourceWatchArgs, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    let node_id = resolve_optional_host_node(cli, args.host.as_deref()).await?;
    let daemon = connect_daemon(cli).await?;
    let client = flotilla_client::resource::ResourceClient::new(daemon);
    let mut watch = client
        .watch(
            flotilla_client::resource::ResourceWatchRequest::builder()
                .kind(args.kind)
                .namespace(args.namespace)
                .maybe_name(args.name)
                .maybe_node_id(node_id)
                .include_replicas(args.include_replicas)
                .maybe_cursor(args.from_cursor)
                .build(),
        )
        .await
        .map_err(|e| color_eyre::eyre::eyre!(e))?;

    loop {
        tokio::select! {
            _ = tokio::signal::ctrl_c() => {
                watch.cancel().await.map_err(|e| color_eyre::eyre::eyre!(e))?;
                return Ok(());
            }
            event = watch.next() => {
                match event.map_err(|e| color_eyre::eyre::eyre!(e))? {
                    Some(response) => print_resource_watch_event(&response, format),
                    None => return Ok(()),
                }
            }
        }
    }
}

fn print_resource_watch_event(response: &flotilla_protocol::ResourceReadEnvelope, format: OutputFormat) {
    match format {
        OutputFormat::Json => println!("{}", flotilla_protocol::output::json_line(response)),
        OutputFormat::Human => {
            println!("{}", flotilla_protocol::output::json_pretty(response));
        }
    }
}

async fn run_attach_plan(daemon: &dyn DaemonHandle, plan: &flotilla_protocol::ResolvedAttachPlan) -> Result<()> {
    let prepared = flotilla_tui::terminal::prepare_attach_plan(plan);
    if let Some(excursion_id) = prepared.excursion_id {
        daemon
            .begin_attach_excursion(excursion_id, prepared.cleanup_actions.clone())
            .await
            .map_err(|error| color_eyre::eyre::eyre!(error))?;
    }
    let attach_result = flotilla_tui::terminal::run_attach_plan(&prepared).map_err(|error| color_eyre::eyre::eyre!(error));
    let cleanup_result = match prepared.excursion_id {
        Some(excursion_id) => daemon.finish_attach_excursion(excursion_id).await.map_err(|error| color_eyre::eyre::eyre!(error)),
        None => Ok(()),
    };
    let status = match (attach_result, cleanup_result) {
        (Ok(status), Ok(())) => status,
        (Err(error), Ok(())) | (Ok(_), Err(error)) => return Err(error),
        (Err(attach_error), Err(cleanup_error)) => {
            return Err(color_eyre::eyre::eyre!("{attach_error}; attach cleanup also failed: {cleanup_error}"));
        }
    };
    terminate_with_attach_status(status)
}

#[derive(Debug, PartialEq, Eq)]
enum AttachExitDisposition {
    Code(i32),
    #[cfg(unix)]
    Signal(i32),
}

fn attach_exit_disposition(status: ExitStatus) -> AttachExitDisposition {
    #[cfg(unix)]
    {
        use std::os::unix::process::ExitStatusExt;
        if let Some(signal) = status.signal() {
            return AttachExitDisposition::Signal(signal);
        }
    }
    AttachExitDisposition::Code(status.code().unwrap_or(1))
}

fn terminate_with_attach_status(status: ExitStatus) -> ! {
    match attach_exit_disposition(status) {
        AttachExitDisposition::Code(code) => std::process::exit(code),
        #[cfg(unix)]
        AttachExitDisposition::Signal(signal) => {
            // Match the old `exec` path: callers should observe the attach
            // process's terminating signal, not a generic Flotilla error.
            unsafe {
                libc::signal(signal, libc::SIG_DFL);
                libc::raise(signal);
            }
            std::process::exit(128 + signal)
        }
    }
}

async fn resolve_host_target(cli: &Cli, subject: &HostName) -> Result<(EnvironmentId, flotilla_protocol::NodeId)> {
    let daemon = connect_daemon(cli).await?;
    let result = daemon
        .execute_query(
            Command { node_id: None, provisioning_target: None, context_repo: None, action: CommandAction::QueryHostList {} },
            uuid::Uuid::new_v4(),
        )
        .await
        .map_err(|e| color_eyre::eyre::eyre!(e))?;

    let CommandValue::HostList(response) = result else {
        return Err(color_eyre::eyre::eyre!("unexpected response while resolving host"));
    };

    select_host_target(&response.hosts, subject)
}

fn select_host_target(
    hosts: &[flotilla_protocol::HostListEntry],
    subject: &HostName,
) -> Result<(EnvironmentId, flotilla_protocol::NodeId)> {
    let mut matches: Vec<_> = hosts.iter().filter(|entry| entry.host_name == *subject).collect();
    match matches.len() {
        0 => Err(color_eyre::eyre::eyre!("unknown host: {subject}")),
        1 => {
            let entry = matches.pop().expect("single host match");
            let environment_id = entry
                .environment_id
                .clone()
                .ok_or_else(|| color_eyre::eyre::eyre!("host {subject} is configured but has no known environment identity"))?;
            let node_id = entry
                .node
                .as_ref()
                .map(|node| node.node_id.clone())
                .ok_or_else(|| color_eyre::eyre::eyre!("host {subject} is configured but has no known node identity"))?;
            Ok((environment_id, node_id))
        }
        _ => {
            let mut ids: Vec<_> = matches
                .iter()
                .map(|entry| entry.environment_id.as_ref().map(EnvironmentId::canonical_string).unwrap_or_else(|| "configured".into()))
                .collect();
            ids.sort();
            Err(color_eyre::eyre::eyre!("ambiguous host: {subject} ({})", ids.join(", ")))
        }
    }
}

async fn resolve_environment_target(
    cli: &Cli,
    target_environment_id: &EnvironmentId,
) -> Result<(flotilla_protocol::ProvisioningTarget, flotilla_protocol::NodeId)> {
    let daemon = connect_daemon(cli).await?;
    let result = daemon
        .execute_query(
            Command { node_id: None, provisioning_target: None, context_repo: None, action: CommandAction::QueryHostList {} },
            uuid::Uuid::new_v4(),
        )
        .await
        .map_err(|e| color_eyre::eyre::eyre!(e))?;

    let CommandValue::HostList(response) = result else {
        return Err(color_eyre::eyre::eyre!("unexpected response while resolving environment"));
    };

    for entry in response.hosts {
        let (Some(environment_id), Some(node)) = (entry.environment_id, entry.node) else {
            continue;
        };
        if environment_id == *target_environment_id {
            return Ok((provisioning_target_for_environment(&entry.host_name, &environment_id), node.node_id));
        }

        let status = daemon
            .execute_query(
                Command {
                    node_id: Some(node.node_id.clone()),
                    provisioning_target: None,
                    context_repo: None,
                    action: CommandAction::QueryHostStatus { target_environment_id: environment_id.clone() },
                },
                uuid::Uuid::new_v4(),
            )
            .await
            .map_err(|e| color_eyre::eyre::eyre!(e));

        let status = match status {
            Ok(status) => status,
            Err(err) => {
                info!(
                    host = %entry.host_name,
                    %environment_id,
                    node_id = %node.node_id,
                    error = %err,
                    "skipping host while resolving environment target"
                );
                continue;
            }
        };

        let CommandValue::HostStatus(response) = status else {
            return Err(color_eyre::eyre::eyre!("unexpected host status response while resolving environment"));
        };

        if response.visible_environments.iter().any(|environment| environment.environment_id() == target_environment_id) {
            return Ok((
                flotilla_protocol::ProvisioningTarget::ExistingEnvironment { host: entry.host_name, env_id: target_environment_id.clone() },
                node.node_id,
            ));
        }
    }

    Err(color_eyre::eyre::eyre!("unknown environment: {target_environment_id}"))
}

fn provisioning_target_for_environment(host: &HostName, environment_id: &EnvironmentId) -> flotilla_protocol::ProvisioningTarget {
    if environment_id.is_host() {
        flotilla_protocol::ProvisioningTarget::Host { host: host.clone() }
    } else {
        flotilla_protocol::ProvisioningTarget::ExistingEnvironment { host: host.clone(), env_id: environment_id.clone() }
    }
}

fn resolve_repo_from_env(cli: &Cli) -> Option<RepoSelector> {
    match (&cli.repo, std::env::var("FLOTILLA_REPO").ok()) {
        (Some(repo), _) => Some(RepoSelector::Query(repo.clone())),
        (None, Some(repo)) if !repo.is_empty() => Some(RepoSelector::Query(repo)),
        _ => None,
    }
}

fn set_context_repo(cmd: &mut Command, cli: &Cli) {
    if cmd.context_repo.is_some() {
        return;
    }
    cmd.context_repo = resolve_repo_from_env(cli);
}

fn inject_repo_context(cmd: &mut Command, cli: &Cli) -> Result<()> {
    let repo_selector = resolve_repo_from_env(cli);

    match &mut cmd.action {
        CommandAction::Checkout { repo, .. } if *repo == RepoSelector::Query(String::new()) => {
            *repo = repo_selector.ok_or_else(|| color_eyre::eyre::eyre!("checkout create requires --repo or FLOTILLA_REPO"))?;
        }
        CommandAction::QueryIssues { repo, .. } if *repo == RepoSelector::Query(String::new()) => {
            *repo = repo_selector.clone().ok_or_else(|| color_eyre::eyre::eyre!("issue search requires --repo or FLOTILLA_REPO"))?;
            cmd.context_repo = repo_selector;
        }
        _ => {
            if cmd.context_repo.is_none() {
                cmd.context_repo = repo_selector;
            }
        }
    }
    Ok(())
}

fn confirm_command(
    command: &mut Command,
    interactive: bool,
    input: &mut dyn std::io::BufRead,
    output: &mut dyn std::io::Write,
) -> Result<bool, String> {
    let CommandAction::MergeChangeRequest { id, confirmed } = &mut command.action else {
        return Ok(true);
    };
    if *confirmed {
        return Ok(true);
    }
    if !interactive {
        return Err("merging a change request non-interactively requires --yes".to_string());
    }

    write!(output, "Merge change request {id} using squash? [y/N] ").map_err(|error| error.to_string())?;
    output.flush().map_err(|error| error.to_string())?;
    let mut response = String::new();
    input.read_line(&mut response).map_err(|error| error.to_string())?;
    if matches!(response.trim().to_ascii_lowercase().as_str(), "y" | "yes") {
        *confirmed = true;
        Ok(true)
    } else {
        writeln!(output, "Merge cancelled.").map_err(|error| error.to_string())?;
        Ok(false)
    }
}

async fn run_confirmed_control_command(cli: &Cli, mut command: Command, format: OutputFormat) -> Result<()> {
    use std::io::IsTerminal;

    let stdin = std::io::stdin();
    let interactive = stdin.is_terminal();
    let mut input = stdin.lock();
    let mut output = std::io::stderr().lock();
    if !confirm_command(&mut command, interactive, &mut input, &mut output).map_err(color_eyre::eyre::Report::msg)? {
        return Ok(());
    }
    run_control_command(cli, command, format).await
}

async fn dispatch(resolved: flotilla_commands::Resolved, cli: &Cli, format: OutputFormat) -> Result<()> {
    use flotilla_commands::{resolved::HostQueryKind, RepoContext, Resolved};
    reset_sigpipe();
    match resolved {
        Resolved::HostQuery { subject, kind } => {
            let (environment_id, node_id) = resolve_host_target(cli, &subject).await?;
            let action = match kind {
                HostQueryKind::Status => CommandAction::QueryHostStatus { target_environment_id: environment_id },
                HostQueryKind::Providers => CommandAction::QueryHostProviders { target_environment_id: environment_id },
            };
            run_confirmed_control_command(
                cli,
                Command { node_id: Some(node_id), provisioning_target: None, context_repo: None, action },
                format,
            )
            .await
        }
        Resolved::Ready(cmd) => run_confirmed_control_command(cli, cmd, format).await,
        Resolved::NeedsContext { mut command, repo, host } => {
            match repo {
                RepoContext::None => {}
                RepoContext::Required => inject_repo_context(&mut command, cli)?,
                RepoContext::Inferred => set_context_repo(&mut command, cli),
            }
            if command.node_id.is_none() {
                match host {
                    flotilla_commands::HostResolution::Explicit(subject) => {
                        let (_environment_id, node_id) = resolve_host_target(cli, &subject).await?;
                        command.node_id = Some(node_id);
                        command.provisioning_target = Some(flotilla_protocol::ProvisioningTarget::Host { host: subject });
                    }
                    flotilla_commands::HostResolution::ExplicitEnvironment(environment_id) => {
                        let (target, node_id) = resolve_environment_target(cli, &environment_id).await?;
                        command.node_id = Some(node_id);
                        command.provisioning_target = Some(target);
                    }
                    _ => {}
                }
            }
            run_confirmed_control_command(cli, command, format).await
        }
    }
}

async fn run_topology_command(cli: &Cli, format: OutputFormat) -> Result<()> {
    reset_sigpipe();
    let daemon = connect_daemon(cli).await?;
    flotilla_tui::cli::run_topology(&*daemon, format).await.map_err(|e| color_eyre::eyre::eyre!(e))
}

fn parse_log_duration(value: &str) -> Result<Duration, String> {
    humantime::parse_duration(value).map_err(|error| error.to_string())
}

async fn run_logs(cli: &Cli, host: Option<&str>, since: Option<Duration>, level: Option<String>, target: Option<String>) -> Result<()> {
    reset_sigpipe();
    let node_id = resolve_optional_host_node(cli, host).await?;
    let daemon = connect_daemon(cli).await?;
    let result = daemon
        .execute_query(
            Command {
                node_id,
                provisioning_target: None,
                context_repo: None,
                action: CommandAction::QueryDaemonLogs {
                    query: flotilla_protocol::commands::DaemonLogQuery {
                        since_seconds: since.map(|duration| duration.as_secs()),
                        level,
                        target,
                    },
                },
            },
            uuid::Uuid::new_v4(),
        )
        .await
        .map_err(|error| color_eyre::eyre::eyre!(error))?;
    match result {
        CommandValue::DaemonLogs { lines } => {
            for line in lines {
                println!("{line}");
            }
            Ok(())
        }
        CommandValue::Error { message } => Err(color_eyre::eyre::eyre!(message)),
        other => Err(color_eyre::eyre::eyre!("unexpected daemon logs response: {other:?}")),
    }
}

async fn run_hook(cli: &Cli, harness: &str, event_type: &str) -> Result<()> {
    use std::io::Read;

    // 1. Resolve harness parser
    let (harness_enum, parser) = agents::parser_for_harness(harness).map_err(|e| color_eyre::eyre::eyre!("unknown harness: {e}"))?;

    // 2. Read native payload from stdin
    let mut payload = Vec::new();
    std::io::stdin().read_to_end(&mut payload).map_err(|e| color_eyre::eyre::eyre!("failed to read stdin: {e}"))?;

    // 3. Parse the event
    let parsed = parser.parse_event(event_type, &payload).map_err(|e| color_eyre::eyre::eyre!("parse error: {e}"))?;

    // 4. Resolve attachable_id from env, or allocate a fresh one.
    // When the daemon receives the event it handles session_id → attachable_id
    // mapping and persistence.
    let attachable_id = match std::env::var("FLOTILLA_ATTACHABLE_ID") {
        Ok(id) if !id.is_empty() => AttachableId::new(id),
        _ => agents::allocate_attachable_id(),
    };

    // 5. Build the event
    let terminal = std::env::var("FLOTILLA_NAMESPACE")
        .ok()
        .filter(|value| !value.is_empty())
        .zip(std::env::var("FLOTILLA_TERMINAL_SESSION").ok().filter(|value| !value.is_empty()))
        .map(|(namespace, session_name)| flotilla_protocol::AgentHookTerminalRef { namespace, session_name });
    let event = AgentHookEvent::builder()
        .attachable_id(attachable_id)
        .harness(harness_enum)
        .event_type(parsed.event_type)
        .maybe_session_id(parsed.session_id)
        .maybe_model(parsed.model)
        .maybe_cwd(parsed.cwd)
        .maybe_terminal(terminal)
        .build();

    // 6. Send to daemon via socket. The daemon owns agent state as a single
    // actor — no file-level races between concurrent hook processes.
    send_hook_event(&cli.socket_path(), event).await
}

/// One-shot client: connect to daemon, send an AgentHook request, read one response, exit.
async fn send_hook_event(socket_path: &std::path::Path, event: AgentHookEvent) -> Result<()> {
    let daemon = flotilla_tui::socket::SocketDaemon::connect(socket_path)
        .await
        .map_err(|error| color_eyre::eyre::eyre!("failed to connect to daemon at {}: {error}", socket_path.display()))?;
    daemon.send_agent_hook(event).await.map_err(|error| color_eyre::eyre::eyre!("daemon error: {error}"))
}

async fn run_hooks_command(command: &HooksSubCommand) -> Result<()> {
    match command {
        HooksSubCommand::Install { harness, user, project, local, plugin } => {
            if harness != "claude-code" {
                return Err(color_eyre::eyre::eyre!("unknown harness: {harness}. Supported: claude-code"));
            }

            if *plugin {
                println!("To install flotilla hooks as a Claude Code plugin:");
                println!();
                println!("  1. Add the marketplace:");
                println!("     /plugin marketplace add flotilla-org/marketplace");
                println!();
                println!("  2. Install the plugin:");
                println!("     /plugin install flotilla-hooks@flotilla-marketplace");
                return Ok(());
            }

            let scope = resolve_settings_scope(*user, *project, *local)?;
            let path = scope.path();

            install_claude_code_hooks(&path)?;
            println!("Installed flotilla hooks for claude-code in {}", path.display());
            Ok(())
        }
        HooksSubCommand::Uninstall { harness, user, project, local } => {
            if harness != "claude-code" {
                return Err(color_eyre::eyre::eyre!("unknown harness: {harness}. Supported: claude-code"));
            }

            let scope = resolve_settings_scope(*user, *project, *local)?;
            let path = scope.path();

            uninstall_claude_code_hooks(&path)?;
            println!("Removed flotilla hooks for claude-code from {}", path.display());
            Ok(())
        }
    }
}

fn run_complete(line: &str, cursor_pos: usize) {
    use clap::CommandFactory;
    let mut root = Cli::command();
    root.build();
    let completions = flotilla_commands::complete::complete(&root, line, cursor_pos);
    for item in completions {
        if let Some(desc) = &item.description {
            println!("{}\t{desc}", item.value);
        } else {
            println!("{}", item.value);
        }
    }
}

fn run_completions(shell: CompletionShell) {
    match shell {
        CompletionShell::Bash => {
            print!(
                r#"_flotilla() {{
    local completions
    completions="$(flotilla complete "${{COMP_LINE}}" "${{COMP_POINT}}" 2>/dev/null)"
    COMPREPLY=()
    while IFS=$'\t' read -r val _desc; do
        [ -n "$val" ] && COMPREPLY+=("$val")
    done <<< "$completions"
}}
complete -F _flotilla flotilla
"#
            );
        }
        CompletionShell::Zsh => {
            // Pass the full command line and absolute cursor position.
            // words[*] is the full line split by words; CURSOR is the absolute byte offset.
            print!(
                r#"#compdef flotilla
_flotilla() {{
    local -a completions
    local line="${{words[*]}}"
    while IFS=$'\t' read -r val desc; do
        [ -n "$val" ] && completions+=("$val:$desc")
    done < <(flotilla complete "$line" "${{CURSOR}}" 2>/dev/null)
    _describe 'flotilla' completions
}}
compdef _flotilla flotilla
"#
            );
        }
        CompletionShell::Fish => {
            println!(
                r#"complete -c flotilla -f -a '(flotilla complete (commandline -cp) (commandline -C) 2>/dev/null | string replace \t \t)'"#
            );
        }
    }
}

enum SettingsScope {
    User,
    Project,
    Local,
}

impl SettingsScope {
    fn path(&self) -> PathBuf {
        match self {
            SettingsScope::User => {
                std::env::var("HOME").map(PathBuf::from).unwrap_or_else(|_| PathBuf::from("~")).join(".claude/settings.json")
            }
            SettingsScope::Project => find_repo_root().join(".claude/settings.json"),
            SettingsScope::Local => find_repo_root().join(".claude/settings.local.json"),
        }
    }
}

/// Walk up from cwd to find the git repo root (directory containing .git).
/// Falls back to cwd if no .git found.
fn find_repo_root() -> PathBuf {
    let mut dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    loop {
        if dir.join(".git").exists() {
            return dir;
        }
        if !dir.pop() {
            return std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
        }
    }
}

fn resolve_settings_scope(user: bool, project: bool, local: bool) -> Result<SettingsScope> {
    match (user, project, local) {
        (true, false, false) => Ok(SettingsScope::User),
        (false, true, false) => Ok(SettingsScope::Project),
        (false, false, true) => Ok(SettingsScope::Local),
        (false, false, false) => Ok(SettingsScope::User), // default
        _ => Err(color_eyre::eyre::eyre!("specify at most one of --user, --project, --local")),
    }
}

fn install_claude_code_hooks(path: &std::path::Path) -> Result<()> {
    let mut settings: serde_json::Value = if path.exists() {
        let content = std::fs::read_to_string(path).map_err(|e| color_eyre::eyre::eyre!("failed to read {}: {e}", path.display()))?;
        serde_json::from_str(&content).map_err(|e| color_eyre::eyre::eyre!("failed to parse {}: {e}", path.display()))?
    } else {
        serde_json::json!({})
    };

    let hooks = settings.as_object_mut().expect("settings is object").entry("hooks").or_insert_with(|| serde_json::json!({}));
    let new_entries = agents::claude_code_hook_entries();
    for (event, matchers) in new_entries.as_object().expect("entries is object") {
        let event_hooks = hooks.as_object_mut().expect("hooks is object").entry(event).or_insert_with(|| serde_json::json!([]));
        let existing_arr = event_hooks.as_array().expect("event hooks is array");
        // Check if flotilla hooks are already present
        let already_installed = existing_arr.iter().any(|m| m.to_string().contains(agents::CLAUDE_CODE_HOOK_COMMAND_PREFIX));
        if !already_installed {
            let arr = event_hooks.as_array_mut().expect("array");
            for entry in matchers.as_array().expect("matchers array") {
                arr.push(entry.clone());
            }
        }
    }

    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| color_eyre::eyre::eyre!("failed to create directory: {e}"))?;
    }
    let json = serde_json::to_string_pretty(&settings).expect("serialize");
    std::fs::write(path, json).map_err(|e| color_eyre::eyre::eyre!("failed to write {}: {e}", path.display()))?;
    Ok(())
}

fn uninstall_claude_code_hooks(path: &std::path::Path) -> Result<()> {
    if !path.exists() {
        return Ok(());
    }
    let content = std::fs::read_to_string(path).map_err(|e| color_eyre::eyre::eyre!("failed to read {}: {e}", path.display()))?;
    let mut settings: serde_json::Value =
        serde_json::from_str(&content).map_err(|e| color_eyre::eyre::eyre!("failed to parse {}: {e}", path.display()))?;

    if let Some(hooks) = settings.get_mut("hooks").and_then(|h| h.as_object_mut()) {
        for (_event, matchers) in hooks.iter_mut() {
            if let Some(arr) = matchers.as_array_mut() {
                arr.retain(|m| !m.to_string().contains(agents::CLAUDE_CODE_HOOK_COMMAND_PREFIX));
            }
        }
        // Remove empty event arrays
        hooks.retain(|_, v| v.as_array().is_none_or(|a| !a.is_empty()));
    }

    let json = serde_json::to_string_pretty(&settings).expect("serialize");
    std::fs::write(path, json).map_err(|e| color_eyre::eyre::eyre!("failed to write {}: {e}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::{
        path::{Path, PathBuf},
        process::Command,
    };

    use clap::Parser;
    use flotilla_protocol::{
        qualified_path::HostId, EnvironmentId, HostListEntry, HostName, NodeId, NodeInfo, PeerConnectionState, ProjectListEntry,
        ProjectListRepository, ProjectListResponse, ProvisioningTarget, RepoIdentity, RepoInfo, RepoLabels, RepositoryKey, ViewAddress,
    };

    use super::{
        attach_exit_disposition, confirm_command, default_project_landing, format_human_resource_value, host_daemon_socket_required,
        provisioning_target_for_environment, replace_host_ids, run_replica_snapshot, select_host_target, select_startup_repo_roots,
        should_reexec_for_incompatible_daemon, show_startup_splash, socket_path_from, AttachExitDisposition, Cli, CommandValue,
        ResourceApplyArgs, ResourceDeleteArgs, ResourceGetArgs, ResourceListArgs, ResourceSubCommand, ResourceWatchArgs, SubCommand,
    };

    fn landing_repo(path: &str, name: &str, key: Option<&str>) -> RepoInfo {
        RepoInfo {
            identity: RepoIdentity { authority: "github.com".into(), path: format!("org/{name}") },
            repository_key: key.map(|key| RepositoryKey(key.into())),
            path: Some(PathBuf::from(path)),
            name: name.into(),
            labels: RepoLabels::default(),
            provider_names: Default::default(),
            provider_health: Default::default(),
            loading: false,
        }
    }

    fn landing_project(name: &str, repositories: &[(&str, Option<&str>)]) -> ProjectListEntry {
        ProjectListEntry::builder()
            .namespace("flotilla".to_string())
            .name(name.to_string())
            .display_name(name.to_string())
            .address(ViewAddress::Project { namespace: "flotilla".into(), name: name.into() })
            .repositories(
                repositories
                    .iter()
                    .map(|(key, subpath)| ProjectListRepository {
                        key: RepositoryKey((*key).into()),
                        slug: None,
                        subpaths: subpath.iter().map(|subpath| (*subpath).to_string()).collect(),
                    })
                    .collect(),
            )
            .default_workflow_ref("single-agent-contained".to_string())
            .build()
    }

    #[test]
    fn attach_exit_disposition_preserves_child_exit_code() {
        let status = Command::new("sh").args(["-c", "exit 42"]).status().expect("run child");
        assert_eq!(attach_exit_disposition(status), AttachExitDisposition::Code(42));
    }

    #[test]
    fn incompatible_daemon_reexecs_once_per_client_build() {
        let mismatch = "daemon protocol version mismatch: daemon has 18, client has 17";
        assert!(should_reexec_for_incompatible_daemon(mismatch, None));
        assert!(!should_reexec_for_incompatible_daemon(mismatch, Some(flotilla_tui::socket::BUILD_ID)));
        assert!(!should_reexec_for_incompatible_daemon("daemon unavailable", None));
    }

    #[cfg(unix)]
    #[test]
    fn attach_exit_disposition_preserves_child_signal() {
        let status = Command::new("sh").args(["-c", "kill -TERM $$"]).status().expect("run child");
        assert_eq!(attach_exit_disposition(status), AttachExitDisposition::Signal(libc::SIGTERM));
    }

    #[test]
    fn explicit_repo_roots_take_precedence_over_cwd_detection() {
        let explicit = vec![PathBuf::from("/repos/one"), PathBuf::from("/repos/two")];

        let roots = select_startup_repo_roots(&explicit, Some(PathBuf::from("/repos/current")));

        assert_eq!(roots, explicit);
    }

    #[test]
    fn explicit_repo_roots_are_deduplicated_in_argument_order() {
        let explicit = vec![PathBuf::from("/repos/one"), PathBuf::from("/repos/two"), PathBuf::from("/repos/one")];

        let roots = select_startup_repo_roots(&explicit, None);

        assert_eq!(roots, vec![PathBuf::from("/repos/one"), PathBuf::from("/repos/two")]);
    }

    #[test]
    fn fresh_landing_resolves_the_detected_repos_whole_repo_project() {
        let repos = vec![
            landing_repo("/repos/other", "other", Some("repo-other")),
            landing_repo("/repos/flotilla", "flotilla", Some("repo-flotilla")),
        ];
        let projects = ProjectListResponse {
            projects: vec![
                landing_project("presentation", &[("repo-flotilla", None), ("repo-other", None)]),
                landing_project("flotilla", &[("repo-flotilla", None)]),
            ],
        };

        let landing = default_project_landing(&repos, &[PathBuf::from("/repos/flotilla")], &projects);

        assert_eq!(
            landing,
            Some((repos[1].identity.clone(), ViewAddress::Project { namespace: "flotilla".into(), name: "flotilla".into() },))
        );
    }

    #[test]
    fn fresh_landing_falls_back_when_detected_repo_has_no_project() {
        let repos = vec![landing_repo("/repos/plain", "plain", Some("repo-plain"))];
        let projects = ProjectListResponse { projects: vec![landing_project("other", &[("repo-other", None)])] };

        assert_eq!(default_project_landing(&repos, &[PathBuf::from("/repos/plain")], &projects), None);
    }

    #[test]
    fn fresh_landing_does_not_confuse_a_subpath_project_for_the_whole_repo_project() {
        let repos = vec![landing_repo("/repos/shared", "shared", Some("repo-shared"))];
        let projects = ProjectListResponse {
            projects: vec![
                landing_project("docs", &[("repo-shared", Some("docs"))]),
                landing_project("shared-a1b2c3d4", &[("repo-shared", None)]),
            ],
        };

        assert_eq!(
            default_project_landing(&repos, &[PathBuf::from("/repos/shared")], &projects),
            Some((repos[0].identity.clone(), ViewAddress::Project { namespace: "flotilla".into(), name: "shared-a1b2c3d4".into() },))
        );
    }

    #[test]
    fn cwd_repo_is_used_when_no_explicit_root_is_given() {
        let roots = select_startup_repo_roots(&[], Some(PathBuf::from("/repos/current")));

        assert_eq!(roots, vec![PathBuf::from("/repos/current")]);
    }

    #[tokio::test]
    async fn scoped_tui_skips_splash_while_full_tui_shows_it() {
        use std::cell::Cell;

        let scoped_view = "convoys/flotilla".parse().expect("valid scoped view");
        let scoped_splash_shown = Cell::new(false);
        show_startup_splash(Some(&scoped_view), || async {
            scoped_splash_shown.set(true);
            Ok(())
        })
        .await
        .expect("scoped startup");

        let full_splash_shown = Cell::new(false);
        show_startup_splash(None, || async {
            full_splash_shown.set(true);
            Ok(())
        })
        .await
        .expect("full startup");

        assert!(!scoped_splash_shown.get());
        assert!(full_splash_shown.get());
    }

    #[test]
    fn cli_parses_topology_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "topology"]).expect("topology cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology)));
        assert!(!cli.json);
    }

    #[test]
    fn cli_parses_topology_with_global_json() {
        let cli = Cli::try_parse_from(["flotilla", "topology", "--json"]).expect("topology json should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology)));
        assert!(cli.json);
    }

    #[test]
    fn cli_parses_remote_filtered_logs() {
        let cli = Cli::try_parse_from([
            "flotilla",
            "logs",
            "--host",
            "feta",
            "--since",
            "2h",
            "--level",
            "warn",
            "--target",
            "flotilla_daemon::peer",
        ])
        .expect("logs cli should parse");

        assert!(matches!(
            cli.command,
            Some(SubCommand::Logs {
                host: Some(host),
                since: Some(since),
                level: Some(level),
                target: Some(target),
            }) if host == "feta"
                && since == std::time::Duration::from_secs(7200)
                && level == "warn"
                && target == "flotilla_daemon::peer"
        ));
    }

    #[test]
    fn cli_parses_ls_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "ls"]).expect("ls cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Ls)));
    }

    #[test]
    fn cli_parses_resource_subcommands() {
        let list = Cli::try_parse_from(["flotilla", "resource", "list", "convoys", "--host", "feta"]).expect("resource list should parse");
        assert!(matches!(
            list.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::List(ResourceListArgs { kind, namespace, host: Some(host), include_replicas: false })
            }) if kind == "convoys" && namespace == "flotilla" && host == "feta"
        ));

        let get = Cli::try_parse_from(["flotilla", "resource", "get", "convoys", "demo", "--namespace", "ops"])
            .expect("resource get should parse");
        assert!(matches!(
            get.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Get(ResourceGetArgs { kind, name, namespace, host: None })
            }) if kind == "convoys" && name == "demo" && namespace == "ops"
        ));

        let delete = Cli::try_parse_from(["flotilla", "resource", "delete", "workflowtemplates", "scratch", "--namespace", "ops"])
            .expect("resource delete should parse");
        assert!(matches!(
            delete.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Delete(ResourceDeleteArgs { kind, name, namespace })
            }) if kind == "workflowtemplates" && name == "scratch" && namespace == "ops"
        ));

        let apply = Cli::try_parse_from(["flotilla", "resource", "apply", "-f", "demand.yaml", "--namespace", "ops"])
            .expect("resource apply should parse");
        assert!(matches!(
            apply.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Apply(ResourceApplyArgs { file, namespace, host: None })
            }) if file.as_path() == Path::new("demand.yaml") && namespace == "ops"
        ));

        let watch = Cli::try_parse_from([
            "flotilla",
            "resource",
            "watch",
            "terminalsessions",
            "session-a",
            "--from-cursor",
            &flotilla_protocol::ResourceCursor::from_position("7", None).to_string(),
            "--json",
        ])
        .expect("resource watch should parse");
        assert!(watch.json);
        assert!(matches!(
            watch.command,
            Some(SubCommand::Resource {
                command: ResourceSubCommand::Watch(ResourceWatchArgs {
                    kind,
                    name: Some(name),
                    namespace,
                    host: None,
                    include_replicas: false,
                    from_cursor: Some(_),
                })
            }) if kind == "terminalsessions" && name == "session-a" && namespace == "flotilla"
        ));
    }

    #[test]
    fn human_resource_rendering_replaces_exact_host_ids_but_not_embedded_object_names() {
        let mut value = serde_json::json!({
            "spec": {"host_ref": "01HXYZ"},
            "metadata": {"name": "host-direct-01HXYZ"},
            "status": {"placement_decision": {"target_host": {"ref": "01HXYZ", "display_name": "kiwi"}}}
        });
        replace_host_ids(&mut value, &std::collections::HashMap::from([("01HXYZ".to_string(), "kiwi".to_string())]));

        assert_eq!(value["spec"]["host_ref"], "kiwi");
        assert_eq!(value["status"]["placement_decision"]["target_host"]["ref"], "kiwi");
        assert_eq!(value["metadata"]["name"], "host-direct-01HXYZ");
    }

    #[test]
    fn human_resource_rendering_falls_back_to_raw_json_when_host_lookup_fails() {
        let value = serde_json::json!({
            "spec": {"host_ref": "01HXYZ"},
            "metadata": {"name": "demo"}
        });

        let rendered = format_human_resource_value(value.clone(), Err::<CommandValue, _>("transient host lookup failure"));

        assert_eq!(rendered, flotilla_protocol::output::json_pretty(&value));
    }

    #[tokio::test]
    async fn replica_snapshot_does_not_spawn_daemon_when_socket_is_missing() {
        let test_dir = std::env::temp_dir().join(format!(
            "flotilla-replica-snapshot-no-spawn-{}",
            std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).expect("clock after epoch").as_nanos()
        ));
        std::fs::create_dir_all(&test_dir).expect("create test dir");
        let config_dir = test_dir.join("config");
        let socket = test_dir.join("missing.sock");
        let cli = Cli::try_parse_from([
            "flotilla",
            "--config-dir",
            config_dir.to_str().expect("config dir utf8"),
            "--socket",
            socket.to_str().expect("socket utf8"),
            "replica-snapshot",
        ])
        .expect("replica snapshot cli should parse");

        let err = run_replica_snapshot(&cli).await.expect_err("missing socket should fail");

        assert!(err.to_string().contains("cannot connect to daemon"), "unexpected error: {err}");
        std::fs::remove_dir_all(&test_dir).expect("remove test dir");
    }

    #[test]
    fn cli_parses_attach_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "attach", "convoy-a/implement/coder"]).expect("attach cli should parse");
        assert!(matches!(
            cli.command,
            Some(SubCommand::Attach { reference, strict: false, take: false, transient: false, host: None })
                if reference == "convoy-a/implement/coder"
        ));
    }

    #[test]
    fn cli_parses_controller_seat_flags() {
        let strict =
            Cli::try_parse_from(["flotilla", "attach", "--strict", "convoy-a/implement/coder"]).expect("strict attach cli should parse");
        assert!(matches!(
            strict.command,
            Some(SubCommand::Attach { reference, strict: true, take: false, transient: false, host: None })
                if reference == "convoy-a/implement/coder"
        ));
        let take = Cli::try_parse_from(["flotilla", "attach", "--take", "convoy-a/implement/coder"]).expect("take attach cli should parse");
        assert!(matches!(
            take.command,
            Some(SubCommand::Attach { reference, strict: false, take: true, transient: false, host: None })
                if reference == "convoy-a/implement/coder"
        ));
        assert!(Cli::try_parse_from(["flotilla", "attach", "--strict", "--take", "convoy-a/implement/coder"]).is_err());
    }

    #[test]
    fn contained_cli_socket_environment_takes_precedence() {
        assert_eq!(
            socket_path_from(
                Some(Path::new("/explicit/flotilla.sock")),
                Path::new("/config"),
                Some(std::ffi::OsStr::new("/run/flotilla.sock")),
            ),
            PathBuf::from("/run/flotilla.sock"),
        );
    }

    #[test]
    fn default_socket_uses_a_dedicated_runtime_directory() {
        assert_eq!(socket_path_from(None, Path::new("/config"), None), PathBuf::from("/config/run/flotilla.sock"));
    }

    #[test]
    fn contained_cli_socket_environment_requires_the_host_daemon() {
        assert!(host_daemon_socket_required(Some(std::ffi::OsStr::new("1"))));
        assert!(!host_daemon_socket_required(None));
    }

    #[test]
    fn cli_parses_internal_transient_attach_target() {
        let cli = Cli::try_parse_from(["flotilla", "attach", "--transient", "--host", "feta", "terminal-scratch"])
            .expect("transient attach cli should parse");
        assert!(matches!(
            cli.command,
            Some(SubCommand::Attach { reference, strict: false, take: false, transient: true, host: Some(host) })
                if reference == "terminal-scratch" && host == "feta"
        ));
    }

    #[test]
    fn cli_parses_host_qualified_materialize_recipe() {
        let cli = Cli::try_parse_from(["flotilla", "attach", "--host", "feta", "terminal-scratch"])
            .expect("host-qualified attach cli should parse");
        assert!(matches!(
            cli.command,
            Some(SubCommand::Attach { reference, strict: false, take: false, transient: false, host: Some(host) })
                if reference == "terminal-scratch" && host == "feta"
        ));
    }

    #[test]
    fn cli_parses_repo_noun() {
        let cli = Cli::try_parse_from(["flotilla", "repo", "owner/repo"]).expect("repo cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Repo(_))));
    }

    #[test]
    fn cli_parses_checkout_noun() {
        let cli = Cli::try_parse_from(["flotilla", "checkout", "my-feature", "remove"]).expect("checkout cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Checkout(_))));
    }

    #[test]
    fn cli_parses_convoy_noun() {
        let cli =
            Cli::try_parse_from(["flotilla", "convoy", "convoy-a", "work", "implement", "complete"]).expect("convoy cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Convoy(_))));
    }

    #[test]
    fn cli_parses_crew_list_and_handoff_grammar() {
        let list = Cli::try_parse_from(["flotilla", "crew", "list"]).expect("crew list should parse");
        assert!(matches!(list.command, Some(SubCommand::Crew(_))));

        let handoff = Cli::try_parse_from(["flotilla", "crew", "reviewer", "handoff", "--message", "Review commit abc123"])
            .expect("crew handoff should parse");
        assert!(matches!(handoff.command, Some(SubCommand::Crew(_))));

        let marked = Cli::try_parse_from(["flotilla", "crew", "@list", "handoff", "--message", "Review commit abc123"])
            .expect("marked crew role should parse");
        assert!(matches!(marked.command, Some(SubCommand::Crew(_))));

        let literal = Cli::try_parse_from(["flotilla", "crew", "--subject", "@reviewer", "handoff", "--message", "Review commit abc123"])
            .expect("literal crew role should parse");
        assert!(matches!(literal.command, Some(SubCommand::Crew(_))));
    }

    #[test]
    fn cli_parses_cr_noun() {
        let cli = Cli::try_parse_from(["flotilla", "cr", "42", "open"]).expect("cr cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Cr(_))));
    }

    #[test]
    fn cli_parses_pr_alias() {
        let cli = Cli::try_parse_from(["flotilla", "pr", "42", "open"]).expect("pr alias should parse");
        assert!(matches!(cli.command, Some(SubCommand::Cr(_))));
    }

    #[test]
    fn cli_parses_issue_noun() {
        let cli = Cli::try_parse_from(["flotilla", "issue", "1", "open"]).expect("issue cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Issue(_))));
    }

    #[test]
    fn cli_parses_agent_noun() {
        let cli = Cli::try_parse_from(["flotilla", "agent", "claude-1", "teleport"]).expect("agent cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Agent(_))));
    }

    #[test]
    fn cli_parses_workspace_noun() {
        let cli = Cli::try_parse_from(["flotilla", "workspace", "feat-ws", "select"]).expect("workspace cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Workspace(_))));
    }

    #[test]
    fn cli_parses_workflow_template_noun() {
        let cli = Cli::try_parse_from(["flotilla", "workflow-template", "scratch", "apply", "--file", "/tmp/x.yaml"])
            .expect("workflow-template cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::WorkflowTemplate(_))));
    }

    #[test]
    fn cli_parses_project_noun() {
        let cli = Cli::try_parse_from(["flotilla", "project", "add", "https://example.com/repo.git", "--name", "my-project"])
            .expect("project cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Project(_))));
    }

    #[test]
    fn cli_parses_convoy_create() {
        let cli = Cli::try_parse_from(["flotilla", "convoy", "my-convoy", "create", "--template", "scratch", "--input", "topic=hi"])
            .expect("convoy create cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Convoy(_))));
    }

    #[test]
    fn cli_parses_host_noun() {
        let cli = Cli::try_parse_from(["flotilla", "host", "list"]).expect("host list should parse");
        assert!(matches!(cli.command, Some(SubCommand::Host(_))));
    }

    #[test]
    fn cli_parses_fleet_health_dashboard() {
        let cli = Cli::try_parse_from(["flotilla", "fleet"]).expect("fleet should parse");
        assert!(matches!(cli.command, Some(SubCommand::Fleet)));
    }

    #[test]
    fn cli_parses_environment_noun() {
        let cli = Cli::try_parse_from(["flotilla", "environment", "host:alpha", "refresh"]).expect("environment cli should parse");
        assert!(matches!(cli.command, Some(SubCommand::Environment(_))));
    }

    #[test]
    fn cli_parses_env_alias() {
        let cli = Cli::try_parse_from(["flotilla", "env", "prov:builder-1", "refresh"]).expect("env alias should parse");
        assert!(matches!(cli.command, Some(SubCommand::Environment(_))));
    }

    #[test]
    fn cli_parses_host_status_with_json() {
        let cli = Cli::try_parse_from(["flotilla", "host", "alpha", "status", "--json"]).expect("host status json should parse");
        assert!(matches!(cli.command, Some(SubCommand::Host(_))));
        assert!(cli.json);
    }

    #[test]
    fn cli_global_json_before_subcommand() {
        let cli = Cli::try_parse_from(["flotilla", "--json", "topology"]).expect("json before subcommand should parse");
        assert!(matches!(cli.command, Some(SubCommand::Topology)));
        assert!(cli.json);
    }

    #[test]
    fn cli_repo_context_flag() {
        let cli = Cli::try_parse_from(["flotilla", "--repo", "owner/repo", "checkout", "create", "--branch", "feat-x"])
            .expect("repo context should parse");
        assert!(matches!(cli.command, Some(SubCommand::Checkout(_))));
        assert_eq!(cli.repo.as_deref(), Some("owner/repo"));
    }

    #[test]
    fn cli_no_subcommand_is_none() {
        let cli = Cli::try_parse_from(["flotilla"]).expect("bare cli should parse");
        assert!(cli.command.is_none());
    }

    #[test]
    fn interactive_merge_confirmation_marks_command_confirmed() {
        let mut command = flotilla_protocol::Command {
            node_id: None,
            provisioning_target: None,
            context_repo: None,
            action: flotilla_protocol::CommandAction::MergeChangeRequest { id: "42".into(), confirmed: false },
        };
        let mut input = std::io::Cursor::new(b"yes\n");
        let mut output = Vec::new();

        let proceed = confirm_command(&mut command, true, &mut input, &mut output).expect("confirmation prompt");

        assert!(proceed);
        assert!(matches!(command.action, flotilla_protocol::CommandAction::MergeChangeRequest { confirmed: true, .. }));
        assert_eq!(String::from_utf8(output).expect("utf8 prompt"), "Merge change request 42 using squash? [y/N] ");
    }

    #[test]
    fn interactive_merge_decline_does_not_dispatch() {
        let mut command = flotilla_protocol::Command {
            node_id: None,
            provisioning_target: None,
            context_repo: None,
            action: flotilla_protocol::CommandAction::MergeChangeRequest { id: "42".into(), confirmed: false },
        };
        let mut input = std::io::Cursor::new(b"n\n");
        let mut output = Vec::new();

        assert!(!confirm_command(&mut command, true, &mut input, &mut output).expect("confirmation prompt"));
        assert!(matches!(command.action, flotilla_protocol::CommandAction::MergeChangeRequest { confirmed: false, .. }));
        assert_eq!(String::from_utf8(output).expect("utf8 prompt"), "Merge change request 42 using squash? [y/N] Merge cancelled.\n");
    }

    #[test]
    fn non_interactive_merge_requires_yes_flag() {
        let mut command = flotilla_protocol::Command {
            node_id: None,
            provisioning_target: None,
            context_repo: None,
            action: flotilla_protocol::CommandAction::MergeChangeRequest { id: "42".into(), confirmed: false },
        };

        let error = confirm_command(&mut command, false, &mut std::io::empty(), &mut std::io::sink())
            .expect_err("non-interactive merge must require explicit confirmation");

        assert_eq!(error, "merging a change request non-interactively requires --yes");
    }

    #[test]
    fn host_target_selection_uses_host_facing_name() {
        let hosts = vec![HostListEntry {
            environment_id: Some(EnvironmentId::host(HostId::new("desktop-a"))),
            host_name: HostName::new("desktop"),
            node: Some(NodeInfo::new(NodeId::new("node-a"), "Builder")),
            is_local: false,
            configured: true,
            connection_status: PeerConnectionState::Connected,
            reconnect: None,
            has_summary: true,
            repo_count: 0,
            work_item_count: 0,
        }];

        let (environment_id, node_id) = select_host_target(&hosts, &HostName::new("desktop")).expect("resolve host");
        assert_eq!(environment_id, EnvironmentId::host(HostId::new("desktop-a")));
        assert_eq!(node_id, NodeId::new("node-a"));
    }

    #[test]
    fn host_target_selection_reports_ambiguity_for_duplicate_host_names() {
        let hosts = vec![
            HostListEntry {
                environment_id: Some(EnvironmentId::host(HostId::new("desktop-a"))),
                host_name: HostName::new("desktop"),
                node: Some(NodeInfo::new(NodeId::new("node-a"), "Desktop")),
                is_local: false,
                configured: true,
                connection_status: PeerConnectionState::Connected,
                reconnect: None,
                has_summary: true,
                repo_count: 0,
                work_item_count: 0,
            },
            HostListEntry {
                environment_id: Some(EnvironmentId::host(HostId::new("desktop-b"))),
                host_name: HostName::new("desktop"),
                node: Some(NodeInfo::new(NodeId::new("node-b"), "Desktop")),
                is_local: false,
                configured: true,
                connection_status: PeerConnectionState::Connected,
                reconnect: None,
                has_summary: true,
                repo_count: 0,
                work_item_count: 0,
            },
        ];

        let err = select_host_target(&hosts, &HostName::new("desktop")).expect_err("duplicate host names should be ambiguous");
        let message = err.to_string();
        assert!(message.contains("ambiguous host: desktop"), "unexpected error: {message}");
        assert!(message.contains("desktop-a"), "unexpected error: {message}");
        assert!(message.contains("desktop-b"), "unexpected error: {message}");
    }

    #[test]
    fn provisioning_target_for_host_environment_uses_host_target() {
        let host = HostName::new("desktop");
        let environment_id = EnvironmentId::host(HostId::new("desktop-a"));

        let target = provisioning_target_for_environment(&host, &environment_id);
        assert_eq!(target, ProvisioningTarget::Host { host });
    }

    #[test]
    fn provisioning_target_for_non_host_environment_preserves_environment_identity() {
        let host = HostName::new("desktop");
        let environment_id = EnvironmentId::new("builder-1");

        let target = provisioning_target_for_environment(&host, &environment_id);
        assert_eq!(target, ProvisioningTarget::ExistingEnvironment { host, env_id: environment_id });
    }
}
